/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnvironmentDeployment { 
    id: number;
    url: string;
    state?: EnvironmentDeployment.StateEnum;
    statusesUrl: string;
    sha: string;
    ref: string;
    task: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace EnvironmentDeployment {
    export type StateEnum = 'PENDING' | 'SUCCESS' | 'ERROR' | 'FAILURE' | 'IN_PROGRESS' | 'QUEUED' | 'INACTIVE' | 'UNKNOWN';
    export const StateEnum = {
        Pending: 'PENDING' as StateEnum,
        Success: 'SUCCESS' as StateEnum,
        Error: 'ERROR' as StateEnum,
        Failure: 'FAILURE' as StateEnum,
        InProgress: 'IN_PROGRESS' as StateEnum,
        Queued: 'QUEUED' as StateEnum,
        Inactive: 'INACTIVE' as StateEnum,
        Unknown: 'UNKNOWN' as StateEnum
    };
}


