/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GitRepository { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    name: string;
    nameWithOwner: string;
    htmlUrl: string;
    description?: string;
    homepage?: string;
    pushedAt: string;
    visibility: GitRepository.VisibilityEnum;
    stargazersCount?: number;
    watchersCount?: number;
    defaultBranch: string;
    hasIssues?: boolean;
    hasProjects?: boolean;
    hasWiki?: boolean;
    'private'?: boolean;
    archived?: boolean;
    disabled?: boolean;
}
export namespace GitRepository {
    export type VisibilityEnum = 'PUBLIC' | 'PRIVATE' | 'INTERNAL' | 'UNKNOWN';
    export const VisibilityEnum = {
        Public: 'PUBLIC' as VisibilityEnum,
        Private: 'PRIVATE' as VisibilityEnum,
        Internal: 'INTERNAL' as VisibilityEnum,
        Unknown: 'UNKNOWN' as VisibilityEnum
    };
}


