/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitRepository } from './git-repository';
import { User } from './user';
import { WorkflowRun } from './workflow-run';


export interface PullRequest { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    number?: number;
    state: PullRequest.StateEnum;
    title: string;
    body?: string;
    htmlUrl: string;
    closedAt?: string;
    commentsCount?: number;
    author?: User;
    assignees?: Set<User>;
    repository?: GitRepository;
    mergedAt?: string;
    mergeCommitSha?: string;
    headSha?: string;
    isMergeable?: boolean;
    mergeableState?: string;
    maintainerCanModify?: boolean;
    commits?: number;
    additions?: number;
    deletions?: number;
    changedFiles?: number;
    mergedBy?: User;
    requestedReviewers?: Set<User>;
    workflowRuns?: Set<WorkflowRun>;
    pullRequest?: boolean;
    draft?: boolean;
    merged?: boolean;
    locked?: boolean;
}
export namespace PullRequest {
    export type StateEnum = 'OPEN' | 'CLOSED';
    export const StateEnum = {
        Open: 'OPEN' as StateEnum,
        Closed: 'CLOSED' as StateEnum
    };
}


