/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RepositoryInfoDTO { 
    id: number;
    name: string;
    nameWithOwner: string;
    description?: string;
    htmlUrl: string;
}

