/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    login: string;
    avatarUrl: string;
    description?: string;
    name: string;
    company?: string;
    blog?: string;
    location?: string;
    email?: string;
    htmlUrl: string;
    type: User.TypeEnum;
    followers?: number;
    following?: number;
}
export namespace User {
    export type TypeEnum = 'USER' | 'ORGANIZATION' | 'BOT';
    export const TypeEnum = {
        User: 'USER' as TypeEnum,
        Organization: 'ORGANIZATION' as TypeEnum,
        Bot: 'BOT' as TypeEnum
    };
}


