/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GitRepository } from './git-repository';
import { PullRequest } from './pull-request';


export interface WorkflowRun { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    repository?: GitRepository;
    pullRequests?: Set<PullRequest>;
    name?: string;
    displayTitle?: string;
    runNumber?: number;
    workflowId?: number;
    runAttempt?: number;
    runStartedAt?: string;
    htmlUrl?: string;
    jobsUrl?: string;
    logsUrl?: string;
    checkSuiteUrl?: string;
    artifactsUrl?: string;
    cancelUrl?: string;
    rerunUrl?: string;
    workflowUrl?: string;
    headBranch?: string;
    headSha?: string;
    status?: WorkflowRun.StatusEnum;
    conclusion?: WorkflowRun.ConclusionEnum;
}
export namespace WorkflowRun {
    export type StatusEnum = 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'ACTION_REQUIRED' | 'CANCELLED' | 'FAILURE' | 'NEUTRAL' | 'SKIPPED' | 'STALE' | 'SUCCESS' | 'TIMED_OUT' | 'REQUESTED' | 'WAITING' | 'PENDING' | 'UNKNOWN';
    export const StatusEnum = {
        Queued: 'QUEUED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum,
        ActionRequired: 'ACTION_REQUIRED' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum,
        Failure: 'FAILURE' as StatusEnum,
        Neutral: 'NEUTRAL' as StatusEnum,
        Skipped: 'SKIPPED' as StatusEnum,
        Stale: 'STALE' as StatusEnum,
        Success: 'SUCCESS' as StatusEnum,
        TimedOut: 'TIMED_OUT' as StatusEnum,
        Requested: 'REQUESTED' as StatusEnum,
        Waiting: 'WAITING' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Unknown: 'UNKNOWN' as StatusEnum
    };
    export type ConclusionEnum = 'ACTION_REQUIRED' | 'CANCELLED' | 'FAILURE' | 'NEUTRAL' | 'SUCCESS' | 'SKIPPED' | 'STALE' | 'TIMED_OUT' | 'STARTUP_FAILURE' | 'UNKNOWN';
    export const ConclusionEnum = {
        ActionRequired: 'ACTION_REQUIRED' as ConclusionEnum,
        Cancelled: 'CANCELLED' as ConclusionEnum,
        Failure: 'FAILURE' as ConclusionEnum,
        Neutral: 'NEUTRAL' as ConclusionEnum,
        Success: 'SUCCESS' as ConclusionEnum,
        Skipped: 'SKIPPED' as ConclusionEnum,
        Stale: 'STALE' as ConclusionEnum,
        TimedOut: 'TIMED_OUT' as ConclusionEnum,
        StartupFailure: 'STARTUP_FAILURE' as ConclusionEnum,
        Unknown: 'UNKNOWN' as ConclusionEnum
    };
}


