/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowRunDTO { 
    id: number;
    name: string;
    displayTitle: string;
    status: WorkflowRunDTO.StatusEnum;
    conclusion?: WorkflowRunDTO.ConclusionEnum;
    htmlUrl: string;
}
export namespace WorkflowRunDTO {
    export type StatusEnum = 'QUEUED' | 'IN_PROGRESS' | 'COMPLETED' | 'ACTION_REQUIRED' | 'CANCELLED' | 'FAILURE' | 'NEUTRAL' | 'SKIPPED' | 'STALE' | 'SUCCESS' | 'TIMED_OUT' | 'REQUESTED' | 'WAITING' | 'PENDING' | 'UNKNOWN';
    export const StatusEnum = {
        Queued: 'QUEUED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Completed: 'COMPLETED' as StatusEnum,
        ActionRequired: 'ACTION_REQUIRED' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum,
        Failure: 'FAILURE' as StatusEnum,
        Neutral: 'NEUTRAL' as StatusEnum,
        Skipped: 'SKIPPED' as StatusEnum,
        Stale: 'STALE' as StatusEnum,
        Success: 'SUCCESS' as StatusEnum,
        TimedOut: 'TIMED_OUT' as StatusEnum,
        Requested: 'REQUESTED' as StatusEnum,
        Waiting: 'WAITING' as StatusEnum,
        Pending: 'PENDING' as StatusEnum,
        Unknown: 'UNKNOWN' as StatusEnum
    };
    export type ConclusionEnum = 'ACTION_REQUIRED' | 'CANCELLED' | 'FAILURE' | 'NEUTRAL' | 'SUCCESS' | 'SKIPPED' | 'STALE' | 'TIMED_OUT' | 'STARTUP_FAILURE' | 'UNKNOWN';
    export const ConclusionEnum = {
        ActionRequired: 'ACTION_REQUIRED' as ConclusionEnum,
        Cancelled: 'CANCELLED' as ConclusionEnum,
        Failure: 'FAILURE' as ConclusionEnum,
        Neutral: 'NEUTRAL' as ConclusionEnum,
        Success: 'SUCCESS' as ConclusionEnum,
        Skipped: 'SKIPPED' as ConclusionEnum,
        Stale: 'STALE' as ConclusionEnum,
        TimedOut: 'TIMED_OUT' as ConclusionEnum,
        StartupFailure: 'STARTUP_FAILURE' as ConclusionEnum,
        Unknown: 'UNKNOWN' as ConclusionEnum
    };
}


