/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowMembershipDTO } from './workflow-membership-dto';


export interface WorkflowGroupDTO { 
    id: number;
    name: string;
    orderIndex: number;
    memberships?: Array<WorkflowMembershipDTO>;
}

