application-server:
  - changed-files:
      - any-glob-to-any-file: server/application-server/**

notification-server:
  - changed-files:
      - any-glob-to-any-file: server/notification/**

webhook-listener:
  - changed-files:
      - any-glob-to-any-file: server/webhook-listener/**

client:
  - changed-files:
      - any-glob-to-any-file: client/**

documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

github-config:
  - changed-files:
      - any-glob-to-any-file: .github/**

keycloakify:
  - changed-files:
      - any-glob-to-any-file: keycloakify/**

feature:
  - head-branch: ['^feature', '^feat']

bug:
  - head-branch: ['^fix', '^bug']