server:
  - changed-files:
      - any-glob-to-any-file: server/**

client:
  - changed-files:
      - any-glob-to-any-file: client/**

documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**

github-config:
  - changed-files:
      - any-glob-to-any-file: .github/**

feature:
  - head-branch: ['^feature', '^feat']

bug:
  - head-branch: ['^fix', '^bug']