services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: helios
      POSTGRES_PASSWORD: helios
      POSTGRES_USER: helios
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  deployment-postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: deployment_service
      POSTGRES_PASSWORD: helios
      POSTGRES_USER: deployment-service
    ports:
      - '5433:5432'
    volumes:
      - deployment-service-data:/var/lib/postgresql/data

  webhook-listener:
    build:
      context: server/webhook-listener
    ports:
      - '4200:4200'
    environment:
      - NATS_AUTH_TOKEN=5760e8ae09adfb2756f9f8cd5cb2caa704cd3f549eaa9298be843ceb165185d815b81f90c680fa7f626b7cd63abf6ac9
      - WEBHOOK_SECRET=$WEBHOOK_SECRET
      - NATS_URL=nats-server

  nats-server:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "/bin/sh", "-c", "sed 's|{{NATS_AUTH_TOKEN}}|'\"$NATS_AUTH_TOKEN\"'|g' /etc/nats/nats-server.conf.template > /etc/nats/nats-server.conf && exec nats-server --config /etc/nats/nats-server.conf" ]
    environment:
      - NATS_AUTH_TOKEN=5760e8ae09adfb2756f9f8cd5cb2caa704cd3f549eaa9298be843ceb165185d815b81f90c680fa7f626b7cd63abf6ac9
    volumes:
      - nats-data:/data
      - ./config/nats-server.conf:/etc/nats/nats-server.conf.template
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8222/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  client:
    container_name: client
    command: sh -c "yarn dev"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "80:4200"

volumes:
  db-data:
  nats-data:
  deployment-service-data:
