services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=helios_test-db
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    command: >
      bash -c "
        set -m

        # Start default entrypoint in the background:
        docker-entrypoint.sh postgres &

        # Wait for Postgres to come up (pg_isready blocks until server is accepting connections)
        until pg_isready -h localhost -p 5432 --timeout=0; do
          echo 'Waiting for Postgres to be ready...';
          sleep 1;
        done;

        # Create 'keycloak' DB if it doesn’t exist
        psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -tc \"SELECT 1 FROM pg_database WHERE datname = 'keycloak'\" | grep -q 1 || psql -U ${POSTGRES_USER} -c \"CREATE DATABASE keycloak;\"

        # Bring Postgres (still running in background) to the foreground
        fg %1
      "
    networks:
      - helios-network

  client:
    entrypoint: npx ng serve --configuration=production --host
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      # Do not expose the client to 80 or 443
      - "90:80"
    restart: always
    networks:
      - helios-network

  application-server:
    build:
      context: ./server/application-server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - DATASOURCE_URL=jdbc:postgresql://postgres/helios_test-db
      - DATASOURCE_USERNAME=test
      - DATASOURCE_PASSWORD=test
      - NATS_SERVER=""
      - NATS_AUTH_TOKEN=""
      - ORGANIZATION_NAME=ls1intum/Helios
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - REPOSITORY_NAME=Helios
      - RUN_ON_STARTUP_COOLDOWN=0
      - OAUTH_ISSUER_URL=http://keycloak:8081/auth/realms/helios
    depends_on:
      - postgres
    networks:
      - helios-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: test
      KC_DB_PASSWORD: test
      KC_HOSTNAME: localhost
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    volumes:
      - ./helios-example-realm.json:/opt/keycloak/data/import/dev-realm-export.json
    command: start-dev --import-realm --http-port=8081
    networks:
      - helios-network

  playwright:
    image: mcr.microsoft.com/playwright:v1.16.1-focal
    entrypoint: npx playwright test
    environment:
      - BASE_URL=http://client:90
    volumes:
      - .:/app:ro
      # Videos, error screenshots and traces are stored in test-results:
      - ./test-results:/app/test-results
      # Snapshot results are stored alongside spec files:
      - ./test:/app/test
    depends_on:
      - client
      - application-server
      - postgres

volumes:
  db-data:
  nats-data:


networks:
  # Create network manually in advance: docker network create helios-network
  helios-network:
    name: helios-network
