/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeploymentDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DeploymentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAllDeployments(extraHttpRequestParams?: any): Observable<Array<DeploymentDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getDeploymentById(id: number, extraHttpRequestParams?: any): Observable<DeploymentDTO>;

    /**
     * 
     * 
     * @param environmentId 
     */
    getDeploymentsByEnvironmentId(environmentId: number, extraHttpRequestParams?: any): Observable<Array<DeploymentDTO>>;

    /**
     * 
     * 
     * @param environmentId 
     */
    getLatestDeploymentByEnvironmentId(environmentId: number, extraHttpRequestParams?: any): Observable<DeploymentDTO>;

}
