/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WorkflowGroupDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GitRepoSettingsControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param repositoryId 
     * @param workflowGroupDTO 
     */
    createWorkflowGroup(repositoryId: number, workflowGroupDTO: WorkflowGroupDTO, extraHttpRequestParams?: any): Observable<WorkflowGroupDTO>;

    /**
     * 
     * 
     * @param repositoryId 
     * @param groupId 
     */
    deleteWorkflowGroup(repositoryId: number, groupId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param repositoryId 
     */
    getGroupsWithWorkflows(repositoryId: number, extraHttpRequestParams?: any): Observable<Array<WorkflowGroupDTO>>;

    /**
     * 
     * 
     * @param repositoryId 
     * @param workflowGroupDTO 
     */
    updateWorkflowGroups(repositoryId: number, workflowGroupDTO: Array<WorkflowGroupDTO>, extraHttpRequestParams?: any): Observable<{}>;

}
