/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PullRequestInfoDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PullRequestControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAllPullRequests(extraHttpRequestParams?: any): Observable<Array<PullRequestInfoDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getPullRequestById(id: number, extraHttpRequestParams?: any): Observable<PullRequestInfoDTO>;

    /**
     * 
     * 
     * @param id 
     */
    getPullRequestByRepositoryId(id: number, extraHttpRequestParams?: any): Observable<Array<PullRequestInfoDTO>>;

    /**
     * 
     * 
     * @param repoId 
     * @param number 
     */
    getPullRequestByRepositoryIdAndNumber(repoId: number, number: number, extraHttpRequestParams?: any): Observable<PullRequestInfoDTO>;

}
