/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WorkflowRunDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WorkflowRunControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param branch 
     * @param commitSha 
     */
    getLatestWorkflowRunsByBranchAndHeadCommitSha(branch: string, commitSha: string, extraHttpRequestParams?: any): Observable<Array<WorkflowRunDTO>>;

    /**
     * 
     * 
     * @param pullRequestId 
     * @param commitSha 
     */
    getLatestWorkflowRunsByPullRequestIdAndHeadCommitSha(pullRequestId: number, commitSha: string, extraHttpRequestParams?: any): Observable<Array<WorkflowRunDTO>>;

}
