/**
 * Helios API
 *
 * Contact: turker.koc@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { WorkflowDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WorkflowControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAllWorkflows(extraHttpRequestParams?: any): Observable<Array<WorkflowDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getWorkflowById(id: number, extraHttpRequestParams?: any): Observable<WorkflowDTO>;

    /**
     * 
     * 
     * @param repositoryId 
     */
    getWorkflowsByRepositoryId(repositoryId: number, extraHttpRequestParams?: any): Observable<Array<WorkflowDTO>>;

    /**
     * 
     * 
     * @param state 
     */
    getWorkflowsByState(state: 'ACTIVE' | 'DELETED' | 'DISABLED_FORK' | 'DISABLED_INACTIVITY' | 'DISABLED_MANUALLY' | 'UNKNOWN', extraHttpRequestParams?: any): Observable<Array<WorkflowDTO>>;

}
