// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type {
  UpdateWorkflowLabelData,
  UpdateWorkflowLabelError,
  DeleteTestTypeData,
  DeleteTestTypeResponse,
  DeleteTestTypeError,
  UpdateTestTypeData,
  UpdateTestTypeResponse,
  UpdateTestTypeError,
  GetGitRepoSettingsData,
  GetGitRepoSettingsResponse,
  GetGitRepoSettingsError,
  UpdateGitRepoSettingsData,
  UpdateGitRepoSettingsResponse,
  UpdateGitRepoSettingsError,
  UpdateWorkflowGroupsData,
  UpdateWorkflowGroupsError,
  UpdateReleaseNameData,
  UpdateReleaseNameError,
  UpdateReleaseNotesData,
  UpdateReleaseNotesError,
  GetEnvironmentByIdData,
  GetEnvironmentByIdResponse,
  GetEnvironmentByIdError,
  UpdateEnvironmentData,
  UpdateEnvironmentResponse,
  UpdateEnvironmentError,
  UnlockEnvironmentData,
  UnlockEnvironmentResponse,
  UnlockEnvironmentError,
  LockEnvironmentData,
  LockEnvironmentResponse,
  LockEnvironmentError,
  ExtendEnvironmentLockData,
  ExtendEnvironmentLockResponse,
  ExtendEnvironmentLockError,
  SyncWorkflowsByRepositoryIdData,
  SyncWorkflowsByRepositoryIdError,
  GetUserSettingsData,
  GetUserSettingsResponse,
  GetUserSettingsError,
  UpdateUserSettingsData,
  UpdateUserSettingsError,
  GetNotificationPreferencesData,
  GetNotificationPreferencesResponse,
  GetNotificationPreferencesError,
  UpdateNotificationPreferencesData,
  UpdateNotificationPreferencesError,
  GetAllTestTypesData,
  GetAllTestTypesResponse,
  GetAllTestTypesError,
  CreateTestTypeData,
  CreateTestTypeResponse,
  CreateTestTypeError,
  CreateWorkflowGroupData,
  CreateWorkflowGroupResponse,
  CreateWorkflowGroupError,
  DeleteReleaseCandidateByNameData,
  DeleteReleaseCandidateByNameResponse,
  DeleteReleaseCandidateByNameError,
  GetAllReleaseInfosData,
  GetAllReleaseInfosResponse,
  GetAllReleaseInfosError,
  CreateReleaseCandidateData,
  CreateReleaseCandidateResponse,
  CreateReleaseCandidateError,
  PublishReleaseDraftData,
  PublishReleaseDraftError,
  GenerateReleaseNotesData,
  GenerateReleaseNotesResponse,
  GenerateReleaseNotesError,
  EvaluateData,
  EvaluateError,
  GetReleaseInfoByNameData,
  GetReleaseInfoByNameResponse,
  GetReleaseInfoByNameError,
  SetPrPinnedByNumberData,
  SetPrPinnedByNumberError,
  SyncEnvironmentsData,
  SyncEnvironmentsResponse,
  SyncEnvironmentsError,
  DeployToEnvironmentData,
  DeployToEnvironmentResponse,
  DeployToEnvironmentError,
  SetBranchPinnedByRepositoryIdAndNameAndUserIdData,
  SetBranchPinnedByRepositoryIdAndNameAndUserIdError,
  HealthCheckData,
  HealthCheckResponse,
  HealthCheckError,
  GetAllWorkflowsData,
  GetAllWorkflowsResponse,
  GetAllWorkflowsError,
  GetWorkflowByIdData,
  GetWorkflowByIdResponse,
  GetWorkflowByIdError,
  GetWorkflowsByStateData,
  GetWorkflowsByStateResponse,
  GetWorkflowsByStateError,
  GetWorkflowsByRepositoryIdData,
  GetWorkflowsByRepositoryIdResponse,
  GetWorkflowsByRepositoryIdError,
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData,
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponse,
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitError,
  GetLatestWorkflowRunsByBranchAndHeadCommitData,
  GetLatestWorkflowRunsByBranchAndHeadCommitResponse,
  GetLatestWorkflowRunsByBranchAndHeadCommitError,
  GetUserPermissionsData,
  GetUserPermissionsResponse,
  GetUserPermissionsError,
  GetLatestTestResultsByPullRequestIdData,
  GetLatestTestResultsByPullRequestIdResponse,
  GetLatestTestResultsByPullRequestIdError,
  GetLatestTestResultsByBranchData,
  GetLatestTestResultsByBranchResponse,
  GetLatestTestResultsByBranchError,
  GetGroupsWithWorkflowsData,
  GetGroupsWithWorkflowsResponse,
  GetGroupsWithWorkflowsError,
  GetAllRepositoriesData,
  GetAllRepositoriesResponse,
  GetAllRepositoriesError,
  GetRepositoryByIdData,
  GetRepositoryByIdResponse,
  GetRepositoryByIdError,
  GetCommitsSinceLastReleaseCandidateData,
  GetCommitsSinceLastReleaseCandidateResponse,
  GetCommitsSinceLastReleaseCandidateError,
  GetAllPullRequestsData,
  GetAllPullRequestsResponse,
  GetAllPullRequestsError,
  GetPullRequestByIdData,
  GetPullRequestByIdResponse,
  GetPullRequestByIdError,
  GetPullRequestByRepositoryIdAndNumberData,
  GetPullRequestByRepositoryIdAndNumberResponse,
  GetPullRequestByRepositoryIdAndNumberError,
  GetPullRequestByRepositoryIdData,
  GetPullRequestByRepositoryIdResponse,
  GetPullRequestByRepositoryIdError,
  GetAllEnvironmentsData,
  GetAllEnvironmentsResponse,
  GetAllEnvironmentsError,
  GetEnvironmentReviewersData,
  GetEnvironmentReviewersResponse,
  GetEnvironmentReviewersError,
  GetEnvironmentsByUserLockingData,
  GetEnvironmentsByUserLockingResponse,
  GetEnvironmentsByUserLockingError,
  GetEnvironmentsByRepositoryIdData,
  GetEnvironmentsByRepositoryIdResponse,
  GetEnvironmentsByRepositoryIdError,
  GetLockHistoryByEnvironmentIdData,
  GetLockHistoryByEnvironmentIdResponse,
  GetLockHistoryByEnvironmentIdError,
  GetAllEnabledEnvironmentsData,
  GetAllEnabledEnvironmentsResponse,
  GetAllEnabledEnvironmentsError,
  GetAllDeploymentsData,
  GetAllDeploymentsResponse,
  GetAllDeploymentsError,
  GetDeploymentByIdData,
  GetDeploymentByIdResponse,
  GetDeploymentByIdError,
  GetDeploymentsByEnvironmentIdData,
  GetDeploymentsByEnvironmentIdResponse,
  GetDeploymentsByEnvironmentIdError,
  GetLatestDeploymentByEnvironmentIdData,
  GetLatestDeploymentByEnvironmentIdResponse,
  GetLatestDeploymentByEnvironmentIdError,
  GetActivityHistoryByEnvironmentIdData,
  GetActivityHistoryByEnvironmentIdResponse,
  GetActivityHistoryByEnvironmentIdError,
  GetCommitByRepositoryIdAndNameData,
  GetCommitByRepositoryIdAndNameResponse,
  GetCommitByRepositoryIdAndNameError,
  GetAllBranchesData,
  GetAllBranchesResponse,
  GetAllBranchesError,
  GetBranchByRepositoryIdAndNameData,
  GetBranchByRepositoryIdAndNameResponse,
  GetBranchByRepositoryIdAndNameError,
  DeleteWorkflowGroupData,
  DeleteWorkflowGroupError,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const updateWorkflowLabel = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkflowLabelData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<unknown, UpdateWorkflowLabelError, ThrowOnError>({
    url: '/api/workflows/{workflowId}/label',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteTestType = <ThrowOnError extends boolean = false>(options: Options<DeleteTestTypeData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteTestTypeResponse, DeleteTestTypeError, ThrowOnError>({
    url: '/api/test-types/{testTypeId}',
    ...options,
  });
};

export const updateTestType = <ThrowOnError extends boolean = false>(options: Options<UpdateTestTypeData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UpdateTestTypeResponse, UpdateTestTypeError, ThrowOnError>({
    url: '/api/test-types/{testTypeId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getGitRepoSettings = <ThrowOnError extends boolean = false>(options: Options<GetGitRepoSettingsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetGitRepoSettingsResponse, GetGitRepoSettingsError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/settings',
    ...options,
  });
};

export const updateGitRepoSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateGitRepoSettingsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UpdateGitRepoSettingsResponse, UpdateGitRepoSettingsError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const updateWorkflowGroups = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkflowGroupsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<unknown, UpdateWorkflowGroupsError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/groups/update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const updateReleaseName = <ThrowOnError extends boolean = false>(options: Options<UpdateReleaseNameData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<unknown, UpdateReleaseNameError, ThrowOnError>({
    url: '/api/release-info/update-name',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const updateReleaseNotes = <ThrowOnError extends boolean = false>(options: Options<UpdateReleaseNotesData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<unknown, UpdateReleaseNotesError, ThrowOnError>({
    url: '/api/release-info/release-notes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getEnvironmentById = <ThrowOnError extends boolean = false>(options: Options<GetEnvironmentByIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetEnvironmentByIdResponse, GetEnvironmentByIdError, ThrowOnError>({
    url: '/api/environments/{id}',
    ...options,
  });
};

export const updateEnvironment = <ThrowOnError extends boolean = false>(options: Options<UpdateEnvironmentData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UpdateEnvironmentResponse, UpdateEnvironmentError, ThrowOnError>({
    url: '/api/environments/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const unlockEnvironment = <ThrowOnError extends boolean = false>(options: Options<UnlockEnvironmentData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<UnlockEnvironmentResponse, UnlockEnvironmentError, ThrowOnError>({
    url: '/api/environments/{id}/unlock',
    ...options,
  });
};

export const lockEnvironment = <ThrowOnError extends boolean = false>(options: Options<LockEnvironmentData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<LockEnvironmentResponse, LockEnvironmentError, ThrowOnError>({
    url: '/api/environments/{id}/lock',
    ...options,
  });
};

export const extendEnvironmentLock = <ThrowOnError extends boolean = false>(options: Options<ExtendEnvironmentLockData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).put<ExtendEnvironmentLockResponse, ExtendEnvironmentLockError, ThrowOnError>({
    url: '/api/environments/{id}/extend-lock',
    ...options,
  });
};

export const syncWorkflowsByRepositoryId = <ThrowOnError extends boolean = false>(options: Options<SyncWorkflowsByRepositoryIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, SyncWorkflowsByRepositoryIdError, ThrowOnError>({
    url: '/api/workflows/repository/{repositoryId}/sync',
    ...options,
  });
};

export const getUserSettings = <ThrowOnError extends boolean = false>(options?: Options<GetUserSettingsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetUserSettingsResponse, GetUserSettingsError, ThrowOnError>({
    url: '/api/user/settings',
    ...options,
  });
};

export const updateUserSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateUserSettingsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, UpdateUserSettingsError, ThrowOnError>({
    url: '/api/user/settings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getNotificationPreferences = <ThrowOnError extends boolean = false>(options?: Options<GetNotificationPreferencesData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetNotificationPreferencesResponse, GetNotificationPreferencesError, ThrowOnError>({
    url: '/api/user/notification-preferences',
    ...options,
  });
};

export const updateNotificationPreferences = <ThrowOnError extends boolean = false>(options: Options<UpdateNotificationPreferencesData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, UpdateNotificationPreferencesError, ThrowOnError>({
    url: '/api/user/notification-preferences',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getAllTestTypes = <ThrowOnError extends boolean = false>(options?: Options<GetAllTestTypesData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllTestTypesResponse, GetAllTestTypesError, ThrowOnError>({
    url: '/api/test-types',
    ...options,
  });
};

export const createTestType = <ThrowOnError extends boolean = false>(options: Options<CreateTestTypeData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateTestTypeResponse, CreateTestTypeError, ThrowOnError>({
    url: '/api/test-types',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const createWorkflowGroup = <ThrowOnError extends boolean = false>(options: Options<CreateWorkflowGroupData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateWorkflowGroupResponse, CreateWorkflowGroupError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/groups/create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteReleaseCandidateByName = <ThrowOnError extends boolean = false>(options: Options<DeleteReleaseCandidateByNameData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<DeleteReleaseCandidateByNameResponse, DeleteReleaseCandidateByNameError, ThrowOnError>({
    url: '/api/release-info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getAllReleaseInfos = <ThrowOnError extends boolean = false>(options?: Options<GetAllReleaseInfosData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllReleaseInfosResponse, GetAllReleaseInfosError, ThrowOnError>({
    url: '/api/release-info',
    ...options,
  });
};

export const createReleaseCandidate = <ThrowOnError extends boolean = false>(options: Options<CreateReleaseCandidateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<CreateReleaseCandidateResponse, CreateReleaseCandidateError, ThrowOnError>({
    url: '/api/release-info',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const publishReleaseDraft = <ThrowOnError extends boolean = false>(options: Options<PublishReleaseDraftData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, PublishReleaseDraftError, ThrowOnError>({
    url: '/api/release-info/publish',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const generateReleaseNotes = <ThrowOnError extends boolean = false>(options: Options<GenerateReleaseNotesData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<GenerateReleaseNotesResponse, GenerateReleaseNotesError, ThrowOnError>({
    url: '/api/release-info/generate-release-notes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const evaluate = <ThrowOnError extends boolean = false>(options: Options<EvaluateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, EvaluateError, ThrowOnError>({
    url: '/api/release-info/evaluate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getReleaseInfoByName = <ThrowOnError extends boolean = false>(options: Options<GetReleaseInfoByNameData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<GetReleaseInfoByNameResponse, GetReleaseInfoByNameError, ThrowOnError>({
    url: '/api/release-info/details',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const setPrPinnedByNumber = <ThrowOnError extends boolean = false>(options: Options<SetPrPinnedByNumberData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<unknown, SetPrPinnedByNumberError, ThrowOnError>({
    url: '/api/pullrequests/{pr}/pin',
    ...options,
  });
};

export const syncEnvironments = <ThrowOnError extends boolean = false>(options?: Options<SyncEnvironmentsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).post<SyncEnvironmentsResponse, SyncEnvironmentsError, ThrowOnError>({
    url: '/api/environments/sync',
    ...options,
  });
};

export const deployToEnvironment = <ThrowOnError extends boolean = false>(options: Options<DeployToEnvironmentData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).post<DeployToEnvironmentResponse, DeployToEnvironmentError, ThrowOnError>({
    url: '/api/deployments/deploy',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const setBranchPinnedByRepositoryIdAndNameAndUserId = <ThrowOnError extends boolean = false>(
  options: Options<SetBranchPinnedByRepositoryIdAndNameAndUserIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<unknown, SetBranchPinnedByRepositoryIdAndNameAndUserIdError, ThrowOnError>({
    url: '/api/branches/repository/{repoId}/pin',
    ...options,
  });
};

export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<HealthCheckResponse, HealthCheckError, ThrowOnError>({
    url: '/status/health',
    ...options,
  });
};

export const getAllWorkflows = <ThrowOnError extends boolean = false>(options?: Options<GetAllWorkflowsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllWorkflowsResponse, GetAllWorkflowsError, ThrowOnError>({
    url: '/api/workflows',
    ...options,
  });
};

export const getWorkflowById = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowByIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetWorkflowByIdResponse, GetWorkflowByIdError, ThrowOnError>({
    url: '/api/workflows/{id}',
    ...options,
  });
};

export const getWorkflowsByState = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowsByStateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetWorkflowsByStateResponse, GetWorkflowsByStateError, ThrowOnError>({
    url: '/api/workflows/state/{state}',
    ...options,
  });
};

export const getWorkflowsByRepositoryId = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowsByRepositoryIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetWorkflowsByRepositoryIdResponse, GetWorkflowsByRepositoryIdError, ThrowOnError>({
    url: '/api/workflows/repository/{repositoryId}',
    ...options,
  });
};

export const getLatestWorkflowRunsByPullRequestIdAndHeadCommit = <ThrowOnError extends boolean = false>(
  options: Options<GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponse, GetLatestWorkflowRunsByPullRequestIdAndHeadCommitError, ThrowOnError>({
    url: '/api/workflows/pr/{pullRequestId}',
    ...options,
  });
};

export const getLatestWorkflowRunsByBranchAndHeadCommit = <ThrowOnError extends boolean = false>(
  options: Options<GetLatestWorkflowRunsByBranchAndHeadCommitData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<GetLatestWorkflowRunsByBranchAndHeadCommitResponse, GetLatestWorkflowRunsByBranchAndHeadCommitError, ThrowOnError>({
    url: '/api/workflows/branch',
    ...options,
  });
};

export const getUserPermissions = <ThrowOnError extends boolean = false>(options?: Options<GetUserPermissionsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetUserPermissionsResponse, GetUserPermissionsError, ThrowOnError>({
    url: '/api/user-permissions',
    ...options,
  });
};

export const getLatestTestResultsByPullRequestId = <ThrowOnError extends boolean = false>(options: Options<GetLatestTestResultsByPullRequestIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetLatestTestResultsByPullRequestIdResponse, GetLatestTestResultsByPullRequestIdError, ThrowOnError>({
    url: '/api/tests/pr/{pullRequestId}',
    ...options,
  });
};

export const getLatestTestResultsByBranch = <ThrowOnError extends boolean = false>(options: Options<GetLatestTestResultsByBranchData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetLatestTestResultsByBranchResponse, GetLatestTestResultsByBranchError, ThrowOnError>({
    url: '/api/tests/branch',
    ...options,
  });
};

export const getGroupsWithWorkflows = <ThrowOnError extends boolean = false>(options: Options<GetGroupsWithWorkflowsData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetGroupsWithWorkflowsResponse, GetGroupsWithWorkflowsError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/groups',
    ...options,
  });
};

export const getAllRepositories = <ThrowOnError extends boolean = false>(options?: Options<GetAllRepositoriesData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllRepositoriesResponse, GetAllRepositoriesError, ThrowOnError>({
    url: '/api/repository',
    ...options,
  });
};

export const getRepositoryById = <ThrowOnError extends boolean = false>(options: Options<GetRepositoryByIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetRepositoryByIdResponse, GetRepositoryByIdError, ThrowOnError>({
    url: '/api/repository/{id}',
    ...options,
  });
};

export const getCommitsSinceLastReleaseCandidate = <ThrowOnError extends boolean = false>(options: Options<GetCommitsSinceLastReleaseCandidateData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetCommitsSinceLastReleaseCandidateResponse, GetCommitsSinceLastReleaseCandidateError, ThrowOnError>({
    url: '/api/release-info/newcommits',
    ...options,
  });
};

export const getAllPullRequests = <ThrowOnError extends boolean = false>(options?: Options<GetAllPullRequestsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllPullRequestsResponse, GetAllPullRequestsError, ThrowOnError>({
    url: '/api/pullrequests',
    ...options,
  });
};

export const getPullRequestById = <ThrowOnError extends boolean = false>(options: Options<GetPullRequestByIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetPullRequestByIdResponse, GetPullRequestByIdError, ThrowOnError>({
    url: '/api/pullrequests/{id}',
    ...options,
  });
};

export const getPullRequestByRepositoryIdAndNumber = <ThrowOnError extends boolean = false>(options: Options<GetPullRequestByRepositoryIdAndNumberData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetPullRequestByRepositoryIdAndNumberResponse, GetPullRequestByRepositoryIdAndNumberError, ThrowOnError>({
    url: '/api/pullrequests/repository/{repoId}/pr/{number}',
    ...options,
  });
};

export const getPullRequestByRepositoryId = <ThrowOnError extends boolean = false>(options: Options<GetPullRequestByRepositoryIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetPullRequestByRepositoryIdResponse, GetPullRequestByRepositoryIdError, ThrowOnError>({
    url: '/api/pullrequests/repository/{id}',
    ...options,
  });
};

export const getAllEnvironments = <ThrowOnError extends boolean = false>(options?: Options<GetAllEnvironmentsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllEnvironmentsResponse, GetAllEnvironmentsError, ThrowOnError>({
    url: '/api/environments',
    ...options,
  });
};

export const getEnvironmentReviewers = <ThrowOnError extends boolean = false>(options: Options<GetEnvironmentReviewersData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetEnvironmentReviewersResponse, GetEnvironmentReviewersError, ThrowOnError>({
    url: '/api/environments/{environmentId}/reviewers',
    ...options,
  });
};

export const getEnvironmentsByUserLocking = <ThrowOnError extends boolean = false>(options?: Options<GetEnvironmentsByUserLockingData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetEnvironmentsByUserLockingResponse, GetEnvironmentsByUserLockingError, ThrowOnError>({
    url: '/api/environments/userLocking',
    ...options,
  });
};

export const getEnvironmentsByRepositoryId = <ThrowOnError extends boolean = false>(options: Options<GetEnvironmentsByRepositoryIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetEnvironmentsByRepositoryIdResponse, GetEnvironmentsByRepositoryIdError, ThrowOnError>({
    url: '/api/environments/repository/{repositoryId}',
    ...options,
  });
};

export const getLockHistoryByEnvironmentId = <ThrowOnError extends boolean = false>(options: Options<GetLockHistoryByEnvironmentIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetLockHistoryByEnvironmentIdResponse, GetLockHistoryByEnvironmentIdError, ThrowOnError>({
    url: '/api/environments/environment/{environmentId}/lockHistory',
    ...options,
  });
};

export const getAllEnabledEnvironments = <ThrowOnError extends boolean = false>(options?: Options<GetAllEnabledEnvironmentsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllEnabledEnvironmentsResponse, GetAllEnabledEnvironmentsError, ThrowOnError>({
    url: '/api/environments/enabled',
    ...options,
  });
};

export const getAllDeployments = <ThrowOnError extends boolean = false>(options?: Options<GetAllDeploymentsData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllDeploymentsResponse, GetAllDeploymentsError, ThrowOnError>({
    url: '/api/deployments',
    ...options,
  });
};

export const getDeploymentById = <ThrowOnError extends boolean = false>(options: Options<GetDeploymentByIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetDeploymentByIdResponse, GetDeploymentByIdError, ThrowOnError>({
    url: '/api/deployments/{id}',
    ...options,
  });
};

export const getDeploymentsByEnvironmentId = <ThrowOnError extends boolean = false>(options: Options<GetDeploymentsByEnvironmentIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetDeploymentsByEnvironmentIdResponse, GetDeploymentsByEnvironmentIdError, ThrowOnError>({
    url: '/api/deployments/environment/{environmentId}',
    ...options,
  });
};

export const getLatestDeploymentByEnvironmentId = <ThrowOnError extends boolean = false>(options: Options<GetLatestDeploymentByEnvironmentIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetLatestDeploymentByEnvironmentIdResponse, GetLatestDeploymentByEnvironmentIdError, ThrowOnError>({
    url: '/api/deployments/environment/{environmentId}/latest',
    ...options,
  });
};

export const getActivityHistoryByEnvironmentId = <ThrowOnError extends boolean = false>(options: Options<GetActivityHistoryByEnvironmentIdData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetActivityHistoryByEnvironmentIdResponse, GetActivityHistoryByEnvironmentIdError, ThrowOnError>({
    url: '/api/deployments/environment/{environmentId}/activity-history',
    ...options,
  });
};

export const getCommitByRepositoryIdAndName = <ThrowOnError extends boolean = false>(options: Options<GetCommitByRepositoryIdAndNameData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetCommitByRepositoryIdAndNameResponse, GetCommitByRepositoryIdAndNameError, ThrowOnError>({
    url: '/api/commits/repository/{repoId}/commit/{sha}',
    ...options,
  });
};

export const getAllBranches = <ThrowOnError extends boolean = false>(options?: Options<GetAllBranchesData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).get<GetAllBranchesResponse, GetAllBranchesError, ThrowOnError>({
    url: '/api/branches',
    ...options,
  });
};

export const getBranchByRepositoryIdAndName = <ThrowOnError extends boolean = false>(options: Options<GetBranchByRepositoryIdAndNameData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).get<GetBranchByRepositoryIdAndNameResponse, GetBranchByRepositoryIdAndNameError, ThrowOnError>({
    url: '/api/branches/repository/{repoId}/branch',
    ...options,
  });
};

export const deleteWorkflowGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkflowGroupData, ThrowOnError>) => {
  return (options.client ?? _heyApiClient).delete<unknown, DeleteWorkflowGroupError, ThrowOnError>({
    url: '/api/settings/{repositoryId}/groups/{groupId}',
    ...options,
  });
};
