// This file is auto-generated by @hey-api/openapi-ts

export type ApiError = {
  status?: number;
  error?: string;
  message?: string;
  path?: string;
  timestamp?: string;
};

export type TestTypeDto = {
  id?: number;
  name?: string;
  artifactName?: string;
  workflowId: number;
};

export type GitRepoSettingsDto = {
  id?: number;
  lockExpirationThreshold?: number;
  lockReservationThreshold?: number;
  packageName?: string;
};

export type WorkflowGroupDto = {
  id: number;
  name: string;
  orderIndex: number;
  memberships?: Array<WorkflowMembershipDto>;
};

export type WorkflowMembershipDto = {
  workflowId: number;
  orderIndex: number;
};

export type ReleaseCandidateNameUpdateDto = {
  oldName?: string;
  newName?: string;
};

export type UpdateReleaseNotesDto = {
  name?: string;
  notes?: string;
};

export type EnvironmentDeployment = {
  id: number;
  url?: string;
  state?: 'REQUESTED' | 'PENDING' | 'WAITING' | 'SUCCESS' | 'ERROR' | 'FAILURE' | 'IN_PROGRESS' | 'QUEUED' | 'INACTIVE' | 'UNKNOWN';
  statusesUrl?: string;
  sha?: string;
  ref?: string;
  task?: string;
  workflowRunHtmlUrl?: string;
  releaseCandidateNames?: Array<string>;
  prName?: string;
  user?: UserInfoDto;
  pullRequestNumber?: number;
  createdAt?: string;
  updatedAt?: string;
  type: 'GITHUB' | 'HELIOS';
};

export type EnvironmentDto = {
  repository?: RepositoryInfoDto;
  id: number;
  name: string;
  displayName?: string;
  locked?: boolean;
  url?: string;
  htmlUrl?: string;
  createdAt?: string;
  updatedAt?: string;
  enabled?: boolean;
  installedApps?: Array<string>;
  description?: string;
  serverUrl?: string;
  statusCheckType?: 'HTTP_STATUS' | 'ARTEMIS_INFO';
  statusUrl?: string;
  deploymentWorkflowBranch?: string;
  latestDeployment?: EnvironmentDeployment;
  latestStatus?: EnvironmentStatusDto;
  lockedBy?: UserInfoDto;
  lockedAt?: string;
  type?: 'TEST' | 'STAGING' | 'PRODUCTION';
  deploymentWorkflow?: WorkflowDto;
  lockExpirationThreshold?: number;
  lockReservationThreshold?: number;
  lockWillExpireAt?: string;
  lockReservationWillExpireAt?: string;
};

export type EnvironmentStatusDto = {
  id: number;
  success: boolean;
  httpStatusCode: number;
  checkedAt: string;
  checkType: 'HTTP_STATUS' | 'ARTEMIS_INFO';
  metadata?: {
    [key: string]: {
      [key: string]: unknown;
    };
  };
};

export type RepositoryInfoDto = {
  id: number;
  name: string;
  nameWithOwner: string;
  description?: string;
  htmlUrl: string;
  updatedAt: string;
  stargazersCount?: number;
  pullRequestCount?: number;
  branchCount?: number;
  environmentCount?: number;
  latestReleaseTagName?: string;
  contributors?: Array<UserInfoDto>;
};

export type UserInfoDto = {
  id: number;
  login: string;
  avatarUrl: string;
  name: string;
  htmlUrl: string;
};

export type WorkflowDto = {
  id: number;
  repository?: RepositoryInfoDto;
  name: string;
  path: string;
  fileNameWithExtension?: string;
  state: 'ACTIVE' | 'DELETED' | 'DISABLED_FORK' | 'DISABLED_INACTIVITY' | 'DISABLED_MANUALLY' | 'UNKNOWN';
  url?: string;
  htmlUrl?: string;
  badgeUrl?: string;
  label: 'NONE' | 'TEST';
  createdAt?: string;
  updatedAt?: string;
};

export type ReleaseCandidateCreateDto = {
  name: string;
  commitSha: string;
  branchName: string;
};

export type ReleaseInfoListDto = {
  name?: string;
  commitSha?: string;
  branchName?: string;
  isPublished?: boolean;
};

export type ReleaseNameDto = {
  name?: string;
};

export type ReleaseEvaluationDto = {
  name?: string;
  isWorking?: boolean;
};

export type BranchInfoDto = {
  name: string;
  commitSha: string;
  aheadBy?: number;
  behindBy?: number;
  isDefault?: boolean;
  isProtected?: boolean;
  isPinned?: boolean;
  updatedAt?: string;
  updatedBy?: UserInfoDto;
  repository?: RepositoryInfoDto;
};

export type CommitInfoDto = {
  sha: string;
  author?: UserInfoDto;
  message?: string;
  authoredAt?: string;
  repository?: RepositoryInfoDto;
};

export type ReleaseCandidateDeploymentDto = {
  id: number;
  type: 'GITHUB' | 'HELIOS';
  environmentId: number;
};

export type ReleaseCandidateEvaluationDto = {
  user: UserInfoDto;
  isWorking?: boolean;
};

export type ReleaseDto = {
  isDraft: boolean;
  isPrerelease: boolean;
  body: string;
  githubUrl: string;
};

export type ReleaseInfoDetailsDto = {
  name: string;
  commit: CommitInfoDto;
  branch?: BranchInfoDto;
  deployments: Array<ReleaseCandidateDeploymentDto>;
  evaluations: Array<ReleaseCandidateEvaluationDto>;
  release?: ReleaseDto;
  createdBy?: UserInfoDto;
  createdAt: string;
  body?: string;
};

export type DeployRequest = {
  environmentId: number;
  branchName: string;
  commitSha: string;
};

export type WorkflowRunDto = {
  id: number;
  name: string;
  displayTitle: string;
  status:
    | 'QUEUED'
    | 'IN_PROGRESS'
    | 'COMPLETED'
    | 'ACTION_REQUIRED'
    | 'CANCELLED'
    | 'FAILURE'
    | 'NEUTRAL'
    | 'SKIPPED'
    | 'STALE'
    | 'SUCCESS'
    | 'TIMED_OUT'
    | 'REQUESTED'
    | 'WAITING'
    | 'PENDING'
    | 'UNKNOWN';
  workflowId: number;
  conclusion?: 'ACTION_REQUIRED' | 'CANCELLED' | 'FAILURE' | 'NEUTRAL' | 'SUCCESS' | 'SKIPPED' | 'STALE' | 'TIMED_OUT' | 'STARTUP_FAILURE' | 'UNKNOWN';
  htmlUrl: string;
  label: 'NONE' | 'TEST';
  testProcessingStatus?: 'PROCESSING' | 'PROCESSED' | 'FAILED';
};

export type GitHubRepositoryRoleDto = {
  permission?: 'ADMIN' | 'WRITE' | 'READ' | 'NONE';
  roleName?: string;
};

export type TestCaseDto = {
  id: number;
  name: string;
  className: string;
  status: 'PASSED' | 'FAILED' | 'ERROR' | 'SKIPPED';
  previousStatus?: 'PASSED' | 'FAILED' | 'ERROR' | 'SKIPPED';
  time: number;
  message?: string;
  stackTrace?: string;
  systemOut?: string;
  errorType?: string;
  flakinessScore?: number;
  defaultBranchFailureRate?: number;
  combinedFailureRate?: number;
  failsInDefaultBranch?: boolean;
};

export type TestResultsDto = {
  testResults: Array<TestTypeResults>;
  isProcessing?: boolean;
};

export type TestSuiteDto = {
  id: number;
  name: string;
  timestamp: string;
  tests: number;
  failures: number;
  errors: number;
  skipped: number;
  time: number;
  systemOut?: string;
  testCases: Array<TestCaseDto>;
};

export type TestTypeResults = {
  testTypeId: number;
  testTypeName: string;
  testSuites: Array<TestSuiteDto>;
  isProcessing: boolean;
  stats: TestTypeStats;
};

export type TestTypeStats = {
  totalSuites: number;
  totalTests: number;
  passed: number;
  failures: number;
  errors: number;
  skipped: number;
  totalTime: number;
  totalUpdates: number;
};

export type CommitsSinceReleaseCandidateDto = {
  aheadBy: number;
  behindBy: number;
  commits: Array<CompareCommitInfoDto>;
  compareUrl?: string;
};

export type CompareCommitInfoDto = {
  sha: string;
  message: string;
  authorName: string;
  authorEmail: string;
  url: string;
};

export type LabelInfoDto = {
  /**
   * The unique identifier of the label
   */
  id: number;
  /**
   * The name of the label
   */
  name: string;
  /**
   * The color of the label as a 6-character hex code (without #)
   */
  color: string;
  /**
   * The repository associated with this label
   */
  repository?: RepositoryInfoDto;
};

export type PullRequestBaseInfoDto = {
  id: number;
  number: number;
  title: string;
  state: 'OPEN' | 'CLOSED';
  isDraft: boolean;
  isMerged: boolean;
  isPinned?: boolean;
  htmlUrl: string;
  createdAt?: string;
  updatedAt?: string;
  author?: UserInfoDto;
  labels?: Array<LabelInfoDto>;
  assignees?: Array<UserInfoDto>;
  reviewers?: Array<UserInfoDto>;
};

export type PullRequestInfoDto = {
  id: number;
  number: number;
  title: string;
  state: 'OPEN' | 'CLOSED';
  isDraft: boolean;
  isMerged: boolean;
  commentsCount: number;
  author?: UserInfoDto;
  labels?: Array<LabelInfoDto>;
  assignees?: Array<UserInfoDto>;
  repository?: RepositoryInfoDto;
  additions: number;
  deletions: number;
  headSha: string;
  headRefName: string;
  headRefRepoNameWithOwner: string;
  mergedAt?: string;
  closedAt?: string;
  htmlUrl: string;
  createdAt?: string;
  updatedAt?: string;
};

export type EnvironmentReviewersDto = {
  preventSelfReview?: boolean;
  reviewers?: Array<Reviewer>;
};

export type Reviewer = {
  id?: number;
  login?: string;
  name?: string;
  type?: string;
};

export type EnvironmentLockHistoryDto = {
  id: number;
  lockedBy?: UserInfoDto;
  unlockedBy?: UserInfoDto;
  lockedAt?: string;
  unlockedAt?: string;
  environment?: EnvironmentDto;
};

export type DeploymentDto = {
  id: number;
  repository?: RepositoryInfoDto;
  url: string;
  state?: 'PENDING' | 'WAITING' | 'SUCCESS' | 'ERROR' | 'FAILURE' | 'IN_PROGRESS' | 'QUEUED' | 'INACTIVE' | 'UNKNOWN';
  statusesUrl: string;
  sha: string;
  ref: string;
  task: string;
  environment: EnvironmentDto;
  user?: UserInfoDto;
  createdAt?: string;
  updatedAt?: string;
};

export type ActivityHistoryDto = {
  type?: string;
  id?: number;
  repository?: RepositoryInfoDto;
  state?: 'PENDING' | 'WAITING' | 'SUCCESS' | 'ERROR' | 'FAILURE' | 'IN_PROGRESS' | 'QUEUED' | 'INACTIVE' | 'UNKNOWN';
  sha?: string;
  ref?: string;
  user?: UserInfoDto;
  user2?: UserInfoDto;
  timestamp?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type BranchDetailsDto = {
  name: string;
  commitSha: string;
  aheadBy?: number;
  behindBy?: number;
  isDefault?: boolean;
  isProtected?: boolean;
  releaseCandidateNames?: Array<string>;
  updatedAt?: string;
  updatedBy?: UserInfoDto;
  repository?: RepositoryInfoDto;
};

export type UpdateWorkflowLabelData = {
  body: 'NONE' | 'TEST';
  path: {
    workflowId: number;
  };
  query?: never;
  url: '/api/workflows/{workflowId}/label';
};

export type UpdateWorkflowLabelErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateWorkflowLabelError = UpdateWorkflowLabelErrors[keyof UpdateWorkflowLabelErrors];

export type UpdateWorkflowLabelResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteTestTypeData = {
  body?: never;
  path: {
    testTypeId: number;
  };
  query?: never;
  url: '/api/test-types/{testTypeId}';
};

export type DeleteTestTypeErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type DeleteTestTypeError = DeleteTestTypeErrors[keyof DeleteTestTypeErrors];

export type DeleteTestTypeResponses = {
  /**
   * No Content
   */
  204: void;
};

export type DeleteTestTypeResponse = DeleteTestTypeResponses[keyof DeleteTestTypeResponses];

export type UpdateTestTypeData = {
  body: TestTypeDto;
  path: {
    testTypeId: number;
  };
  query?: never;
  url: '/api/test-types/{testTypeId}';
};

export type UpdateTestTypeErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateTestTypeError = UpdateTestTypeErrors[keyof UpdateTestTypeErrors];

export type UpdateTestTypeResponses = {
  /**
   * OK
   */
  200: TestTypeDto;
};

export type UpdateTestTypeResponse = UpdateTestTypeResponses[keyof UpdateTestTypeResponses];

export type GetGitRepoSettingsData = {
  body?: never;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/settings';
};

export type GetGitRepoSettingsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetGitRepoSettingsError = GetGitRepoSettingsErrors[keyof GetGitRepoSettingsErrors];

export type GetGitRepoSettingsResponses = {
  /**
   * OK
   */
  200: GitRepoSettingsDto;
};

export type GetGitRepoSettingsResponse = GetGitRepoSettingsResponses[keyof GetGitRepoSettingsResponses];

export type UpdateGitRepoSettingsData = {
  body: GitRepoSettingsDto;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/settings';
};

export type UpdateGitRepoSettingsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateGitRepoSettingsError = UpdateGitRepoSettingsErrors[keyof UpdateGitRepoSettingsErrors];

export type UpdateGitRepoSettingsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type UpdateGitRepoSettingsResponse = UpdateGitRepoSettingsResponses[keyof UpdateGitRepoSettingsResponses];

export type UpdateWorkflowGroupsData = {
  body: Array<WorkflowGroupDto>;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/groups/update';
};

export type UpdateWorkflowGroupsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateWorkflowGroupsError = UpdateWorkflowGroupsErrors[keyof UpdateWorkflowGroupsErrors];

export type UpdateWorkflowGroupsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type UpdateReleaseNameData = {
  body: ReleaseCandidateNameUpdateDto;
  path?: never;
  query?: never;
  url: '/api/release-info/update-name';
};

export type UpdateReleaseNameErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateReleaseNameError = UpdateReleaseNameErrors[keyof UpdateReleaseNameErrors];

export type UpdateReleaseNameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type UpdateReleaseNotesData = {
  body: UpdateReleaseNotesDto;
  path?: never;
  query?: never;
  url: '/api/release-info/release-notes';
};

export type UpdateReleaseNotesErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateReleaseNotesError = UpdateReleaseNotesErrors[keyof UpdateReleaseNotesErrors];

export type UpdateReleaseNotesResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetEnvironmentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/environments/{id}';
};

export type GetEnvironmentByIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetEnvironmentByIdError = GetEnvironmentByIdErrors[keyof GetEnvironmentByIdErrors];

export type GetEnvironmentByIdResponses = {
  /**
   * OK
   */
  200: EnvironmentDto;
};

export type GetEnvironmentByIdResponse = GetEnvironmentByIdResponses[keyof GetEnvironmentByIdResponses];

export type UpdateEnvironmentData = {
  body: EnvironmentDto;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/environments/{id}';
};

export type UpdateEnvironmentErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UpdateEnvironmentError = UpdateEnvironmentErrors[keyof UpdateEnvironmentErrors];

export type UpdateEnvironmentResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type UpdateEnvironmentResponse = UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses];

export type UnlockEnvironmentData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/environments/{id}/unlock';
};

export type UnlockEnvironmentErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type UnlockEnvironmentError = UnlockEnvironmentErrors[keyof UnlockEnvironmentErrors];

export type UnlockEnvironmentResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type UnlockEnvironmentResponse = UnlockEnvironmentResponses[keyof UnlockEnvironmentResponses];

export type LockEnvironmentData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/environments/{id}/lock';
};

export type LockEnvironmentErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type LockEnvironmentError = LockEnvironmentErrors[keyof LockEnvironmentErrors];

export type LockEnvironmentResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type LockEnvironmentResponse = LockEnvironmentResponses[keyof LockEnvironmentResponses];

export type ExtendEnvironmentLockData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/environments/{id}/extend-lock';
};

export type ExtendEnvironmentLockErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type ExtendEnvironmentLockError = ExtendEnvironmentLockErrors[keyof ExtendEnvironmentLockErrors];

export type ExtendEnvironmentLockResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type ExtendEnvironmentLockResponse = ExtendEnvironmentLockResponses[keyof ExtendEnvironmentLockResponses];

export type SyncWorkflowsByRepositoryIdData = {
  body?: never;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/workflows/repository/{repositoryId}/sync';
};

export type SyncWorkflowsByRepositoryIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type SyncWorkflowsByRepositoryIdError = SyncWorkflowsByRepositoryIdErrors[keyof SyncWorkflowsByRepositoryIdErrors];

export type SyncWorkflowsByRepositoryIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetAllTestTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/test-types';
};

export type GetAllTestTypesErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllTestTypesError = GetAllTestTypesErrors[keyof GetAllTestTypesErrors];

export type GetAllTestTypesResponses = {
  /**
   * OK
   */
  200: Array<TestTypeDto>;
};

export type GetAllTestTypesResponse = GetAllTestTypesResponses[keyof GetAllTestTypesResponses];

export type CreateTestTypeData = {
  body: TestTypeDto;
  path?: never;
  query?: never;
  url: '/api/test-types';
};

export type CreateTestTypeErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type CreateTestTypeError = CreateTestTypeErrors[keyof CreateTestTypeErrors];

export type CreateTestTypeResponses = {
  /**
   * Created
   */
  201: TestTypeDto;
};

export type CreateTestTypeResponse = CreateTestTypeResponses[keyof CreateTestTypeResponses];

export type CreateWorkflowGroupData = {
  body: WorkflowGroupDto;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/groups/create';
};

export type CreateWorkflowGroupErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type CreateWorkflowGroupError = CreateWorkflowGroupErrors[keyof CreateWorkflowGroupErrors];

export type CreateWorkflowGroupResponses = {
  /**
   * OK
   */
  200: WorkflowGroupDto;
};

export type CreateWorkflowGroupResponse = CreateWorkflowGroupResponses[keyof CreateWorkflowGroupResponses];

export type DeleteReleaseCandidateByNameData = {
  body: ReleaseNameDto;
  path?: never;
  query?: never;
  url: '/api/release-info';
};

export type DeleteReleaseCandidateByNameErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type DeleteReleaseCandidateByNameError = DeleteReleaseCandidateByNameErrors[keyof DeleteReleaseCandidateByNameErrors];

export type DeleteReleaseCandidateByNameResponses = {
  /**
   * OK
   */
  200: ReleaseInfoListDto;
};

export type DeleteReleaseCandidateByNameResponse = DeleteReleaseCandidateByNameResponses[keyof DeleteReleaseCandidateByNameResponses];

export type GetAllReleaseInfosData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/release-info';
};

export type GetAllReleaseInfosErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllReleaseInfosError = GetAllReleaseInfosErrors[keyof GetAllReleaseInfosErrors];

export type GetAllReleaseInfosResponses = {
  /**
   * OK
   */
  200: Array<ReleaseInfoListDto>;
};

export type GetAllReleaseInfosResponse = GetAllReleaseInfosResponses[keyof GetAllReleaseInfosResponses];

export type CreateReleaseCandidateData = {
  body: ReleaseCandidateCreateDto;
  path?: never;
  query?: never;
  url: '/api/release-info';
};

export type CreateReleaseCandidateErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type CreateReleaseCandidateError = CreateReleaseCandidateErrors[keyof CreateReleaseCandidateErrors];

export type CreateReleaseCandidateResponses = {
  /**
   * OK
   */
  200: ReleaseInfoListDto;
};

export type CreateReleaseCandidateResponse = CreateReleaseCandidateResponses[keyof CreateReleaseCandidateResponses];

export type PublishReleaseDraftData = {
  body: ReleaseNameDto;
  path?: never;
  query?: never;
  url: '/api/release-info/publish';
};

export type PublishReleaseDraftErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type PublishReleaseDraftError = PublishReleaseDraftErrors[keyof PublishReleaseDraftErrors];

export type PublishReleaseDraftResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GenerateReleaseNotesData = {
  body: ReleaseNameDto;
  path?: never;
  query?: never;
  url: '/api/release-info/generate-release-notes';
};

export type GenerateReleaseNotesErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GenerateReleaseNotesError = GenerateReleaseNotesErrors[keyof GenerateReleaseNotesErrors];

export type GenerateReleaseNotesResponses = {
  /**
   * OK
   */
  200: string;
};

export type GenerateReleaseNotesResponse = GenerateReleaseNotesResponses[keyof GenerateReleaseNotesResponses];

export type EvaluateData = {
  body: ReleaseEvaluationDto;
  path?: never;
  query?: never;
  url: '/api/release-info/evaluate';
};

export type EvaluateErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type EvaluateError = EvaluateErrors[keyof EvaluateErrors];

export type EvaluateResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetReleaseInfoByNameData = {
  body: ReleaseNameDto;
  path?: never;
  query?: never;
  url: '/api/release-info/details';
};

export type GetReleaseInfoByNameErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetReleaseInfoByNameError = GetReleaseInfoByNameErrors[keyof GetReleaseInfoByNameErrors];

export type GetReleaseInfoByNameResponses = {
  /**
   * OK
   */
  200: ReleaseInfoDetailsDto;
};

export type GetReleaseInfoByNameResponse = GetReleaseInfoByNameResponses[keyof GetReleaseInfoByNameResponses];

export type SetPrPinnedByNumberData = {
  body?: never;
  path: {
    pr: number;
  };
  query: {
    isPinned: boolean;
  };
  url: '/api/pullrequests/{pr}/pin';
};

export type SetPrPinnedByNumberErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type SetPrPinnedByNumberError = SetPrPinnedByNumberErrors[keyof SetPrPinnedByNumberErrors];

export type SetPrPinnedByNumberResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type SyncEnvironmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environments/sync';
};

export type SyncEnvironmentsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type SyncEnvironmentsError = SyncEnvironmentsErrors[keyof SyncEnvironmentsErrors];

export type SyncEnvironmentsResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type SyncEnvironmentsResponse = SyncEnvironmentsResponses[keyof SyncEnvironmentsResponses];

export type DeployToEnvironmentData = {
  body: DeployRequest;
  path?: never;
  query?: never;
  url: '/api/deployments/deploy';
};

export type DeployToEnvironmentErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type DeployToEnvironmentError = DeployToEnvironmentErrors[keyof DeployToEnvironmentErrors];

export type DeployToEnvironmentResponses = {
  /**
   * OK
   */
  200: string;
};

export type DeployToEnvironmentResponse = DeployToEnvironmentResponses[keyof DeployToEnvironmentResponses];

export type SetBranchPinnedByRepositoryIdAndNameAndUserIdData = {
  body?: never;
  path: {
    repoId: number;
  };
  query: {
    name: string;
    isPinned: boolean;
  };
  url: '/api/branches/repository/{repoId}/pin';
};

export type SetBranchPinnedByRepositoryIdAndNameAndUserIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type SetBranchPinnedByRepositoryIdAndNameAndUserIdError = SetBranchPinnedByRepositoryIdAndNameAndUserIdErrors[keyof SetBranchPinnedByRepositoryIdAndNameAndUserIdErrors];

export type SetBranchPinnedByRepositoryIdAndNameAndUserIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/status/health';
};

export type HealthCheckErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
  /**
   * OK
   */
  200: string;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type GetAllWorkflowsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/workflows';
};

export type GetAllWorkflowsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllWorkflowsError = GetAllWorkflowsErrors[keyof GetAllWorkflowsErrors];

export type GetAllWorkflowsResponses = {
  /**
   * OK
   */
  200: Array<WorkflowDto>;
};

export type GetAllWorkflowsResponse = GetAllWorkflowsResponses[keyof GetAllWorkflowsResponses];

export type GetWorkflowByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/workflows/{id}';
};

export type GetWorkflowByIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetWorkflowByIdError = GetWorkflowByIdErrors[keyof GetWorkflowByIdErrors];

export type GetWorkflowByIdResponses = {
  /**
   * OK
   */
  200: WorkflowDto;
};

export type GetWorkflowByIdResponse = GetWorkflowByIdResponses[keyof GetWorkflowByIdResponses];

export type GetWorkflowsByStateData = {
  body?: never;
  path: {
    state: 'ACTIVE' | 'DELETED' | 'DISABLED_FORK' | 'DISABLED_INACTIVITY' | 'DISABLED_MANUALLY' | 'UNKNOWN';
  };
  query?: never;
  url: '/api/workflows/state/{state}';
};

export type GetWorkflowsByStateErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetWorkflowsByStateError = GetWorkflowsByStateErrors[keyof GetWorkflowsByStateErrors];

export type GetWorkflowsByStateResponses = {
  /**
   * OK
   */
  200: Array<WorkflowDto>;
};

export type GetWorkflowsByStateResponse = GetWorkflowsByStateResponses[keyof GetWorkflowsByStateResponses];

export type GetWorkflowsByRepositoryIdData = {
  body?: never;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/workflows/repository/{repositoryId}';
};

export type GetWorkflowsByRepositoryIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetWorkflowsByRepositoryIdError = GetWorkflowsByRepositoryIdErrors[keyof GetWorkflowsByRepositoryIdErrors];

export type GetWorkflowsByRepositoryIdResponses = {
  /**
   * OK
   */
  200: Array<WorkflowDto>;
};

export type GetWorkflowsByRepositoryIdResponse = GetWorkflowsByRepositoryIdResponses[keyof GetWorkflowsByRepositoryIdResponses];

export type GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData = {
  body?: never;
  path: {
    pullRequestId: number;
  };
  query?: never;
  url: '/api/workflows/pr/{pullRequestId}';
};

export type GetLatestWorkflowRunsByPullRequestIdAndHeadCommitErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLatestWorkflowRunsByPullRequestIdAndHeadCommitError =
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitErrors[keyof GetLatestWorkflowRunsByPullRequestIdAndHeadCommitErrors];

export type GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponses = {
  /**
   * OK
   */
  200: Array<WorkflowRunDto>;
};

export type GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponse =
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponses[keyof GetLatestWorkflowRunsByPullRequestIdAndHeadCommitResponses];

export type GetLatestWorkflowRunsByBranchAndHeadCommitData = {
  body?: never;
  path?: never;
  query: {
    branch: string;
  };
  url: '/api/workflows/branch';
};

export type GetLatestWorkflowRunsByBranchAndHeadCommitErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLatestWorkflowRunsByBranchAndHeadCommitError = GetLatestWorkflowRunsByBranchAndHeadCommitErrors[keyof GetLatestWorkflowRunsByBranchAndHeadCommitErrors];

export type GetLatestWorkflowRunsByBranchAndHeadCommitResponses = {
  /**
   * OK
   */
  200: Array<WorkflowRunDto>;
};

export type GetLatestWorkflowRunsByBranchAndHeadCommitResponse = GetLatestWorkflowRunsByBranchAndHeadCommitResponses[keyof GetLatestWorkflowRunsByBranchAndHeadCommitResponses];

export type GetUserPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/user-permissions';
};

export type GetUserPermissionsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetUserPermissionsError = GetUserPermissionsErrors[keyof GetUserPermissionsErrors];

export type GetUserPermissionsResponses = {
  /**
   * OK
   */
  200: GitHubRepositoryRoleDto;
};

export type GetUserPermissionsResponse = GetUserPermissionsResponses[keyof GetUserPermissionsResponses];

export type GetLatestTestResultsByPullRequestIdData = {
  body?: never;
  path: {
    pullRequestId: number;
  };
  query?: {
    page?: number;
    size?: number;
    search?: string;
    onlyFailed?: boolean;
  };
  url: '/api/tests/pr/{pullRequestId}';
};

export type GetLatestTestResultsByPullRequestIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLatestTestResultsByPullRequestIdError = GetLatestTestResultsByPullRequestIdErrors[keyof GetLatestTestResultsByPullRequestIdErrors];

export type GetLatestTestResultsByPullRequestIdResponses = {
  /**
   * OK
   */
  200: TestResultsDto;
};

export type GetLatestTestResultsByPullRequestIdResponse = GetLatestTestResultsByPullRequestIdResponses[keyof GetLatestTestResultsByPullRequestIdResponses];

export type GetLatestTestResultsByBranchData = {
  body?: never;
  path?: never;
  query: {
    branch: string;
    page?: number;
    size?: number;
    search?: string;
    onlyFailed?: boolean;
  };
  url: '/api/tests/branch';
};

export type GetLatestTestResultsByBranchErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLatestTestResultsByBranchError = GetLatestTestResultsByBranchErrors[keyof GetLatestTestResultsByBranchErrors];

export type GetLatestTestResultsByBranchResponses = {
  /**
   * OK
   */
  200: TestResultsDto;
};

export type GetLatestTestResultsByBranchResponse = GetLatestTestResultsByBranchResponses[keyof GetLatestTestResultsByBranchResponses];

export type GetGroupsWithWorkflowsData = {
  body?: never;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/groups';
};

export type GetGroupsWithWorkflowsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetGroupsWithWorkflowsError = GetGroupsWithWorkflowsErrors[keyof GetGroupsWithWorkflowsErrors];

export type GetGroupsWithWorkflowsResponses = {
  /**
   * OK
   */
  200: Array<WorkflowGroupDto>;
};

export type GetGroupsWithWorkflowsResponse = GetGroupsWithWorkflowsResponses[keyof GetGroupsWithWorkflowsResponses];

export type GetAllRepositoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/repository';
};

export type GetAllRepositoriesErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllRepositoriesError = GetAllRepositoriesErrors[keyof GetAllRepositoriesErrors];

export type GetAllRepositoriesResponses = {
  /**
   * OK
   */
  200: Array<RepositoryInfoDto>;
};

export type GetAllRepositoriesResponse = GetAllRepositoriesResponses[keyof GetAllRepositoriesResponses];

export type GetRepositoryByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/repository/{id}';
};

export type GetRepositoryByIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetRepositoryByIdError = GetRepositoryByIdErrors[keyof GetRepositoryByIdErrors];

export type GetRepositoryByIdResponses = {
  /**
   * OK
   */
  200: RepositoryInfoDto;
};

export type GetRepositoryByIdResponse = GetRepositoryByIdResponses[keyof GetRepositoryByIdResponses];

export type GetCommitsSinceLastReleaseCandidateData = {
  body?: never;
  path?: never;
  query: {
    branch: string;
  };
  url: '/api/release-info/newcommits';
};

export type GetCommitsSinceLastReleaseCandidateErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetCommitsSinceLastReleaseCandidateError = GetCommitsSinceLastReleaseCandidateErrors[keyof GetCommitsSinceLastReleaseCandidateErrors];

export type GetCommitsSinceLastReleaseCandidateResponses = {
  /**
   * OK
   */
  200: CommitsSinceReleaseCandidateDto;
};

export type GetCommitsSinceLastReleaseCandidateResponse = GetCommitsSinceLastReleaseCandidateResponses[keyof GetCommitsSinceLastReleaseCandidateResponses];

export type GetAllPullRequestsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/pullrequests';
};

export type GetAllPullRequestsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllPullRequestsError = GetAllPullRequestsErrors[keyof GetAllPullRequestsErrors];

export type GetAllPullRequestsResponses = {
  /**
   * OK
   */
  200: Array<PullRequestBaseInfoDto>;
};

export type GetAllPullRequestsResponse = GetAllPullRequestsResponses[keyof GetAllPullRequestsResponses];

export type GetPullRequestByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/pullrequests/{id}';
};

export type GetPullRequestByIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetPullRequestByIdError = GetPullRequestByIdErrors[keyof GetPullRequestByIdErrors];

export type GetPullRequestByIdResponses = {
  /**
   * OK
   */
  200: PullRequestInfoDto;
};

export type GetPullRequestByIdResponse = GetPullRequestByIdResponses[keyof GetPullRequestByIdResponses];

export type GetPullRequestByRepositoryIdAndNumberData = {
  body?: never;
  path: {
    repoId: number;
    number: number;
  };
  query?: never;
  url: '/api/pullrequests/repository/{repoId}/pr/{number}';
};

export type GetPullRequestByRepositoryIdAndNumberErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetPullRequestByRepositoryIdAndNumberError = GetPullRequestByRepositoryIdAndNumberErrors[keyof GetPullRequestByRepositoryIdAndNumberErrors];

export type GetPullRequestByRepositoryIdAndNumberResponses = {
  /**
   * OK
   */
  200: PullRequestInfoDto;
};

export type GetPullRequestByRepositoryIdAndNumberResponse = GetPullRequestByRepositoryIdAndNumberResponses[keyof GetPullRequestByRepositoryIdAndNumberResponses];

export type GetPullRequestByRepositoryIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/pullrequests/repository/{id}';
};

export type GetPullRequestByRepositoryIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetPullRequestByRepositoryIdError = GetPullRequestByRepositoryIdErrors[keyof GetPullRequestByRepositoryIdErrors];

export type GetPullRequestByRepositoryIdResponses = {
  /**
   * OK
   */
  200: Array<PullRequestInfoDto>;
};

export type GetPullRequestByRepositoryIdResponse = GetPullRequestByRepositoryIdResponses[keyof GetPullRequestByRepositoryIdResponses];

export type GetAllEnvironmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environments';
};

export type GetAllEnvironmentsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllEnvironmentsError = GetAllEnvironmentsErrors[keyof GetAllEnvironmentsErrors];

export type GetAllEnvironmentsResponses = {
  /**
   * OK
   */
  200: Array<EnvironmentDto>;
};

export type GetAllEnvironmentsResponse = GetAllEnvironmentsResponses[keyof GetAllEnvironmentsResponses];

export type GetEnvironmentReviewersData = {
  body?: never;
  path: {
    environmentId: number;
  };
  query?: never;
  url: '/api/environments/{environmentId}/reviewers';
};

export type GetEnvironmentReviewersErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetEnvironmentReviewersError = GetEnvironmentReviewersErrors[keyof GetEnvironmentReviewersErrors];

export type GetEnvironmentReviewersResponses = {
  /**
   * OK
   */
  200: EnvironmentReviewersDto;
};

export type GetEnvironmentReviewersResponse = GetEnvironmentReviewersResponses[keyof GetEnvironmentReviewersResponses];

export type GetEnvironmentsByUserLockingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environments/userLocking';
};

export type GetEnvironmentsByUserLockingErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetEnvironmentsByUserLockingError = GetEnvironmentsByUserLockingErrors[keyof GetEnvironmentsByUserLockingErrors];

export type GetEnvironmentsByUserLockingResponses = {
  /**
   * OK
   */
  200: EnvironmentLockHistoryDto;
};

export type GetEnvironmentsByUserLockingResponse = GetEnvironmentsByUserLockingResponses[keyof GetEnvironmentsByUserLockingResponses];

export type GetEnvironmentsByRepositoryIdData = {
  body?: never;
  path: {
    repositoryId: number;
  };
  query?: never;
  url: '/api/environments/repository/{repositoryId}';
};

export type GetEnvironmentsByRepositoryIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetEnvironmentsByRepositoryIdError = GetEnvironmentsByRepositoryIdErrors[keyof GetEnvironmentsByRepositoryIdErrors];

export type GetEnvironmentsByRepositoryIdResponses = {
  /**
   * OK
   */
  200: Array<EnvironmentDto>;
};

export type GetEnvironmentsByRepositoryIdResponse = GetEnvironmentsByRepositoryIdResponses[keyof GetEnvironmentsByRepositoryIdResponses];

export type GetLockHistoryByEnvironmentIdData = {
  body?: never;
  path: {
    environmentId: number;
  };
  query?: never;
  url: '/api/environments/environment/{environmentId}/lockHistory';
};

export type GetLockHistoryByEnvironmentIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLockHistoryByEnvironmentIdError = GetLockHistoryByEnvironmentIdErrors[keyof GetLockHistoryByEnvironmentIdErrors];

export type GetLockHistoryByEnvironmentIdResponses = {
  /**
   * OK
   */
  200: Array<EnvironmentLockHistoryDto>;
};

export type GetLockHistoryByEnvironmentIdResponse = GetLockHistoryByEnvironmentIdResponses[keyof GetLockHistoryByEnvironmentIdResponses];

export type GetAllEnabledEnvironmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/environments/enabled';
};

export type GetAllEnabledEnvironmentsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllEnabledEnvironmentsError = GetAllEnabledEnvironmentsErrors[keyof GetAllEnabledEnvironmentsErrors];

export type GetAllEnabledEnvironmentsResponses = {
  /**
   * OK
   */
  200: Array<EnvironmentDto>;
};

export type GetAllEnabledEnvironmentsResponse = GetAllEnabledEnvironmentsResponses[keyof GetAllEnabledEnvironmentsResponses];

export type GetAllDeploymentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/deployments';
};

export type GetAllDeploymentsErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllDeploymentsError = GetAllDeploymentsErrors[keyof GetAllDeploymentsErrors];

export type GetAllDeploymentsResponses = {
  /**
   * OK
   */
  200: Array<DeploymentDto>;
};

export type GetAllDeploymentsResponse = GetAllDeploymentsResponses[keyof GetAllDeploymentsResponses];

export type GetDeploymentByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: '/api/deployments/{id}';
};

export type GetDeploymentByIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetDeploymentByIdError = GetDeploymentByIdErrors[keyof GetDeploymentByIdErrors];

export type GetDeploymentByIdResponses = {
  /**
   * OK
   */
  200: DeploymentDto;
};

export type GetDeploymentByIdResponse = GetDeploymentByIdResponses[keyof GetDeploymentByIdResponses];

export type GetDeploymentsByEnvironmentIdData = {
  body?: never;
  path: {
    environmentId: number;
  };
  query?: never;
  url: '/api/deployments/environment/{environmentId}';
};

export type GetDeploymentsByEnvironmentIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetDeploymentsByEnvironmentIdError = GetDeploymentsByEnvironmentIdErrors[keyof GetDeploymentsByEnvironmentIdErrors];

export type GetDeploymentsByEnvironmentIdResponses = {
  /**
   * OK
   */
  200: Array<DeploymentDto>;
};

export type GetDeploymentsByEnvironmentIdResponse = GetDeploymentsByEnvironmentIdResponses[keyof GetDeploymentsByEnvironmentIdResponses];

export type GetLatestDeploymentByEnvironmentIdData = {
  body?: never;
  path: {
    environmentId: number;
  };
  query?: never;
  url: '/api/deployments/environment/{environmentId}/latest';
};

export type GetLatestDeploymentByEnvironmentIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetLatestDeploymentByEnvironmentIdError = GetLatestDeploymentByEnvironmentIdErrors[keyof GetLatestDeploymentByEnvironmentIdErrors];

export type GetLatestDeploymentByEnvironmentIdResponses = {
  /**
   * OK
   */
  200: DeploymentDto;
};

export type GetLatestDeploymentByEnvironmentIdResponse = GetLatestDeploymentByEnvironmentIdResponses[keyof GetLatestDeploymentByEnvironmentIdResponses];

export type GetActivityHistoryByEnvironmentIdData = {
  body?: never;
  path: {
    environmentId: number;
  };
  query?: never;
  url: '/api/deployments/environment/{environmentId}/activity-history';
};

export type GetActivityHistoryByEnvironmentIdErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetActivityHistoryByEnvironmentIdError = GetActivityHistoryByEnvironmentIdErrors[keyof GetActivityHistoryByEnvironmentIdErrors];

export type GetActivityHistoryByEnvironmentIdResponses = {
  /**
   * OK
   */
  200: Array<ActivityHistoryDto>;
};

export type GetActivityHistoryByEnvironmentIdResponse = GetActivityHistoryByEnvironmentIdResponses[keyof GetActivityHistoryByEnvironmentIdResponses];

export type GetCommitByRepositoryIdAndNameData = {
  body?: never;
  path: {
    repoId: number;
    sha: string;
  };
  query?: never;
  url: '/api/commits/repository/{repoId}/commit/{sha}';
};

export type GetCommitByRepositoryIdAndNameErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetCommitByRepositoryIdAndNameError = GetCommitByRepositoryIdAndNameErrors[keyof GetCommitByRepositoryIdAndNameErrors];

export type GetCommitByRepositoryIdAndNameResponses = {
  /**
   * OK
   */
  200: CommitInfoDto;
};

export type GetCommitByRepositoryIdAndNameResponse = GetCommitByRepositoryIdAndNameResponses[keyof GetCommitByRepositoryIdAndNameResponses];

export type GetAllBranchesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/branches';
};

export type GetAllBranchesErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetAllBranchesError = GetAllBranchesErrors[keyof GetAllBranchesErrors];

export type GetAllBranchesResponses = {
  /**
   * OK
   */
  200: Array<BranchInfoDto>;
};

export type GetAllBranchesResponse = GetAllBranchesResponses[keyof GetAllBranchesResponses];

export type GetBranchByRepositoryIdAndNameData = {
  body?: never;
  path: {
    repoId: number;
  };
  query: {
    name: string;
  };
  url: '/api/branches/repository/{repoId}/branch';
};

export type GetBranchByRepositoryIdAndNameErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type GetBranchByRepositoryIdAndNameError = GetBranchByRepositoryIdAndNameErrors[keyof GetBranchByRepositoryIdAndNameErrors];

export type GetBranchByRepositoryIdAndNameResponses = {
  /**
   * OK
   */
  200: BranchDetailsDto;
};

export type GetBranchByRepositoryIdAndNameResponse = GetBranchByRepositoryIdAndNameResponses[keyof GetBranchByRepositoryIdAndNameResponses];

export type DeleteWorkflowGroupData = {
  body?: never;
  path: {
    repositoryId: number;
    groupId: number;
  };
  query?: never;
  url: '/api/settings/{repositoryId}/groups/{groupId}';
};

export type DeleteWorkflowGroupErrors = {
  /**
   * Conflict
   */
  409: ApiError;
};

export type DeleteWorkflowGroupError = DeleteWorkflowGroupErrors[keyof DeleteWorkflowGroupErrors];

export type DeleteWorkflowGroupResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
