// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  updateWorkflowLabel,
  deleteTestType,
  updateTestType,
  getGitRepoSettings,
  updateGitRepoSettings,
  updateWorkflowGroups,
  updateReleaseName,
  updateReleaseNotes,
  getEnvironmentById,
  updateEnvironment,
  unlockEnvironment,
  lockEnvironment,
  extendEnvironmentLock,
  syncWorkflowsByRepositoryId,
  getUserSettings,
  updateUserSettings,
  getNotificationPreferences,
  updateNotificationPreferences,
  getAllTestTypes,
  createTestType,
  rotateSecret,
  createWorkflowGroup,
  deleteReleaseCandidateByName,
  getAllReleaseInfos,
  createReleaseCandidate,
  publishReleaseDraft,
  generateReleaseNotes,
  evaluate,
  getReleaseInfoByName,
  setPrPinnedByNumber,
  syncEnvironments,
  update,
  deployToEnvironment,
  cancelDeployment,
  setBranchPinnedByRepositoryIdAndNameAndUserId,
  healthCheck,
  getAllWorkflows,
  getWorkflowById,
  getWorkflowsByState,
  getWorkflowsByRepositoryId,
  getLatestWorkflowRunsByPullRequestIdAndHeadCommit,
  getLatestWorkflowRunsByBranchAndHeadCommit,
  getUserPermissions,
  getLatestTestResultsByPullRequestId,
  getLatestTestResultsByBranch,
  getGroupsWithWorkflows,
  getAllRepositories,
  getRepositoryById,
  getCommitsSinceLastReleaseCandidate,
  getPullRequests,
  getPullRequestById,
  getPullRequestByRepositoryIdAndNumber,
  getPullRequestByRepositoryId,
  getAllEnvironments,
  getEnvironmentReviewers,
  getEnvironmentsByUserLocking,
  getEnvironmentsByRepositoryId,
  getLockHistoryByEnvironmentId,
  getAllEnabledEnvironments,
  getAllDeployments,
  getDeploymentById,
  getWorkflowJobStatus,
  getDeploymentsByEnvironmentId,
  getLatestDeploymentByEnvironmentId,
  getActivityHistoryByEnvironmentId,
  getCommitByRepositoryIdAndName,
  getAllBranches,
  getBranchByRepositoryIdAndName,
  deleteWorkflowGroup,
} from '../sdk.gen';
import { type MutationOptions, queryOptions, infiniteQueryOptions, type InfiniteData } from '@tanstack/angular-query-experimental';
import type {
  UpdateWorkflowLabelData,
  UpdateWorkflowLabelError,
  DeleteTestTypeData,
  DeleteTestTypeError,
  DeleteTestTypeResponse,
  UpdateTestTypeData,
  UpdateTestTypeError,
  UpdateTestTypeResponse,
  GetGitRepoSettingsData,
  UpdateGitRepoSettingsData,
  UpdateGitRepoSettingsError,
  UpdateGitRepoSettingsResponse,
  UpdateWorkflowGroupsData,
  UpdateWorkflowGroupsError,
  UpdateReleaseNameData,
  UpdateReleaseNameError,
  UpdateReleaseNotesData,
  UpdateReleaseNotesError,
  GetEnvironmentByIdData,
  UpdateEnvironmentData,
  UpdateEnvironmentError,
  UpdateEnvironmentResponse,
  UnlockEnvironmentData,
  UnlockEnvironmentError,
  UnlockEnvironmentResponse,
  LockEnvironmentData,
  LockEnvironmentError,
  LockEnvironmentResponse,
  ExtendEnvironmentLockData,
  ExtendEnvironmentLockError,
  ExtendEnvironmentLockResponse,
  SyncWorkflowsByRepositoryIdData,
  SyncWorkflowsByRepositoryIdError,
  GetUserSettingsData,
  UpdateUserSettingsData,
  UpdateUserSettingsError,
  GetNotificationPreferencesData,
  UpdateNotificationPreferencesData,
  UpdateNotificationPreferencesError,
  GetAllTestTypesData,
  CreateTestTypeData,
  CreateTestTypeError,
  CreateTestTypeResponse,
  RotateSecretData,
  RotateSecretError,
  RotateSecretResponse,
  CreateWorkflowGroupData,
  CreateWorkflowGroupError,
  CreateWorkflowGroupResponse,
  DeleteReleaseCandidateByNameData,
  DeleteReleaseCandidateByNameError,
  DeleteReleaseCandidateByNameResponse,
  GetAllReleaseInfosData,
  CreateReleaseCandidateData,
  CreateReleaseCandidateError,
  CreateReleaseCandidateResponse,
  PublishReleaseDraftData,
  PublishReleaseDraftError,
  GenerateReleaseNotesData,
  GenerateReleaseNotesError,
  GenerateReleaseNotesResponse,
  EvaluateData,
  EvaluateError,
  GetReleaseInfoByNameData,
  GetReleaseInfoByNameError,
  GetReleaseInfoByNameResponse,
  SetPrPinnedByNumberData,
  SetPrPinnedByNumberError,
  SyncEnvironmentsData,
  SyncEnvironmentsError,
  SyncEnvironmentsResponse,
  UpdateData,
  UpdateError,
  DeployToEnvironmentData,
  DeployToEnvironmentError,
  DeployToEnvironmentResponse,
  CancelDeploymentData,
  CancelDeploymentError,
  CancelDeploymentResponse,
  SetBranchPinnedByRepositoryIdAndNameAndUserIdData,
  SetBranchPinnedByRepositoryIdAndNameAndUserIdError,
  HealthCheckData,
  GetAllWorkflowsData,
  GetWorkflowByIdData,
  GetWorkflowsByStateData,
  GetWorkflowsByRepositoryIdData,
  GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData,
  GetLatestWorkflowRunsByBranchAndHeadCommitData,
  GetUserPermissionsData,
  GetLatestTestResultsByPullRequestIdData,
  GetLatestTestResultsByPullRequestIdError,
  GetLatestTestResultsByPullRequestIdResponse,
  GetLatestTestResultsByBranchData,
  GetLatestTestResultsByBranchError,
  GetLatestTestResultsByBranchResponse,
  GetGroupsWithWorkflowsData,
  GetAllRepositoriesData,
  GetRepositoryByIdData,
  GetCommitsSinceLastReleaseCandidateData,
  GetPullRequestsData,
  GetPullRequestsError,
  GetPullRequestsResponse,
  GetPullRequestByIdData,
  GetPullRequestByRepositoryIdAndNumberData,
  GetPullRequestByRepositoryIdData,
  GetAllEnvironmentsData,
  GetEnvironmentReviewersData,
  GetEnvironmentsByUserLockingData,
  GetEnvironmentsByRepositoryIdData,
  GetLockHistoryByEnvironmentIdData,
  GetAllEnabledEnvironmentsData,
  GetAllDeploymentsData,
  GetDeploymentByIdData,
  GetWorkflowJobStatusData,
  GetDeploymentsByEnvironmentIdData,
  GetLatestDeploymentByEnvironmentIdData,
  GetActivityHistoryByEnvironmentIdData,
  GetCommitByRepositoryIdAndNameData,
  GetAllBranchesData,
  GetBranchByRepositoryIdAndNameData,
  DeleteWorkflowGroupData,
  DeleteWorkflowGroupError,
} from '../types.gen';
import { client } from '../client.gen';

export const updateWorkflowLabelMutation = (
  options?: Partial<Options<UpdateWorkflowLabelData>>
): MutationOptions<unknown, UpdateWorkflowLabelError, Options<UpdateWorkflowLabelData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateWorkflowLabelError, Options<UpdateWorkflowLabelData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateWorkflowLabel({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteTestTypeMutation = (
  options?: Partial<Options<DeleteTestTypeData>>
): MutationOptions<DeleteTestTypeResponse, DeleteTestTypeError, Options<DeleteTestTypeData>> => {
  const mutationOptions: MutationOptions<DeleteTestTypeResponse, DeleteTestTypeError, Options<DeleteTestTypeData>> = {
    mutationFn: async fnOptions => {
      const { data } = await deleteTestType({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateTestTypeMutation = (
  options?: Partial<Options<UpdateTestTypeData>>
): MutationOptions<UpdateTestTypeResponse, UpdateTestTypeError, Options<UpdateTestTypeData>> => {
  const mutationOptions: MutationOptions<UpdateTestTypeResponse, UpdateTestTypeError, Options<UpdateTestTypeData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateTestType({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getGitRepoSettingsQueryKey = (options: Options<GetGitRepoSettingsData>) => createQueryKey('getGitRepoSettings', options);

export const getGitRepoSettingsOptions = (options: Options<GetGitRepoSettingsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGitRepoSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGitRepoSettingsQueryKey(options),
  });
};

export const updateGitRepoSettingsMutation = (
  options?: Partial<Options<UpdateGitRepoSettingsData>>
): MutationOptions<UpdateGitRepoSettingsResponse, UpdateGitRepoSettingsError, Options<UpdateGitRepoSettingsData>> => {
  const mutationOptions: MutationOptions<UpdateGitRepoSettingsResponse, UpdateGitRepoSettingsError, Options<UpdateGitRepoSettingsData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateGitRepoSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateWorkflowGroupsMutation = (
  options?: Partial<Options<UpdateWorkflowGroupsData>>
): MutationOptions<unknown, UpdateWorkflowGroupsError, Options<UpdateWorkflowGroupsData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateWorkflowGroupsError, Options<UpdateWorkflowGroupsData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateWorkflowGroups({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateReleaseNameMutation = (options?: Partial<Options<UpdateReleaseNameData>>): MutationOptions<unknown, UpdateReleaseNameError, Options<UpdateReleaseNameData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateReleaseNameError, Options<UpdateReleaseNameData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateReleaseName({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateReleaseNotesMutation = (
  options?: Partial<Options<UpdateReleaseNotesData>>
): MutationOptions<unknown, UpdateReleaseNotesError, Options<UpdateReleaseNotesData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateReleaseNotesError, Options<UpdateReleaseNotesData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateReleaseNotes({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEnvironmentByIdQueryKey = (options: Options<GetEnvironmentByIdData>) => createQueryKey('getEnvironmentById', options);

export const getEnvironmentByIdOptions = (options: Options<GetEnvironmentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentByIdQueryKey(options),
  });
};

export const updateEnvironmentMutation = (
  options?: Partial<Options<UpdateEnvironmentData>>
): MutationOptions<UpdateEnvironmentResponse, UpdateEnvironmentError, Options<UpdateEnvironmentData>> => {
  const mutationOptions: MutationOptions<UpdateEnvironmentResponse, UpdateEnvironmentError, Options<UpdateEnvironmentData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const unlockEnvironmentMutation = (
  options?: Partial<Options<UnlockEnvironmentData>>
): MutationOptions<UnlockEnvironmentResponse, UnlockEnvironmentError, Options<UnlockEnvironmentData>> => {
  const mutationOptions: MutationOptions<UnlockEnvironmentResponse, UnlockEnvironmentError, Options<UnlockEnvironmentData>> = {
    mutationFn: async fnOptions => {
      const { data } = await unlockEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const lockEnvironmentMutation = (
  options?: Partial<Options<LockEnvironmentData>>
): MutationOptions<LockEnvironmentResponse, LockEnvironmentError, Options<LockEnvironmentData>> => {
  const mutationOptions: MutationOptions<LockEnvironmentResponse, LockEnvironmentError, Options<LockEnvironmentData>> = {
    mutationFn: async fnOptions => {
      const { data } = await lockEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const extendEnvironmentLockMutation = (
  options?: Partial<Options<ExtendEnvironmentLockData>>
): MutationOptions<ExtendEnvironmentLockResponse, ExtendEnvironmentLockError, Options<ExtendEnvironmentLockData>> => {
  const mutationOptions: MutationOptions<ExtendEnvironmentLockResponse, ExtendEnvironmentLockError, Options<ExtendEnvironmentLockData>> = {
    mutationFn: async fnOptions => {
      const { data } = await extendEnvironmentLock({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const syncWorkflowsByRepositoryIdMutation = (
  options?: Partial<Options<SyncWorkflowsByRepositoryIdData>>
): MutationOptions<unknown, SyncWorkflowsByRepositoryIdError, Options<SyncWorkflowsByRepositoryIdData>> => {
  const mutationOptions: MutationOptions<unknown, SyncWorkflowsByRepositoryIdError, Options<SyncWorkflowsByRepositoryIdData>> = {
    mutationFn: async fnOptions => {
      const { data } = await syncWorkflowsByRepositoryId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserSettingsQueryKey = (options?: Options<GetUserSettingsData>) => createQueryKey('getUserSettings', options);

export const getUserSettingsOptions = (options?: Options<GetUserSettingsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserSettingsQueryKey(options),
  });
};

export const updateUserSettingsMutation = (
  options?: Partial<Options<UpdateUserSettingsData>>
): MutationOptions<unknown, UpdateUserSettingsError, Options<UpdateUserSettingsData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateUserSettingsError, Options<UpdateUserSettingsData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateUserSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNotificationPreferencesQueryKey = (options?: Options<GetNotificationPreferencesData>) => createQueryKey('getNotificationPreferences', options);

export const getNotificationPreferencesOptions = (options?: Options<GetNotificationPreferencesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNotificationPreferences({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNotificationPreferencesQueryKey(options),
  });
};

export const updateNotificationPreferencesMutation = (
  options?: Partial<Options<UpdateNotificationPreferencesData>>
): MutationOptions<unknown, UpdateNotificationPreferencesError, Options<UpdateNotificationPreferencesData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateNotificationPreferencesError, Options<UpdateNotificationPreferencesData>> = {
    mutationFn: async fnOptions => {
      const { data } = await updateNotificationPreferences({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAllTestTypesQueryKey = (options?: Options<GetAllTestTypesData>) => createQueryKey('getAllTestTypes', options);

export const getAllTestTypesOptions = (options?: Options<GetAllTestTypesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllTestTypes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllTestTypesQueryKey(options),
  });
};

export const createTestTypeMutation = (
  options?: Partial<Options<CreateTestTypeData>>
): MutationOptions<CreateTestTypeResponse, CreateTestTypeError, Options<CreateTestTypeData>> => {
  const mutationOptions: MutationOptions<CreateTestTypeResponse, CreateTestTypeError, Options<CreateTestTypeData>> = {
    mutationFn: async fnOptions => {
      const { data } = await createTestType({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const rotateSecretMutation = (options?: Partial<Options<RotateSecretData>>): MutationOptions<RotateSecretResponse, RotateSecretError, Options<RotateSecretData>> => {
  const mutationOptions: MutationOptions<RotateSecretResponse, RotateSecretError, Options<RotateSecretData>> = {
    mutationFn: async fnOptions => {
      const { data } = await rotateSecret({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const createWorkflowGroupMutation = (
  options?: Partial<Options<CreateWorkflowGroupData>>
): MutationOptions<CreateWorkflowGroupResponse, CreateWorkflowGroupError, Options<CreateWorkflowGroupData>> => {
  const mutationOptions: MutationOptions<CreateWorkflowGroupResponse, CreateWorkflowGroupError, Options<CreateWorkflowGroupData>> = {
    mutationFn: async fnOptions => {
      const { data } = await createWorkflowGroup({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteReleaseCandidateByNameMutation = (
  options?: Partial<Options<DeleteReleaseCandidateByNameData>>
): MutationOptions<DeleteReleaseCandidateByNameResponse, DeleteReleaseCandidateByNameError, Options<DeleteReleaseCandidateByNameData>> => {
  const mutationOptions: MutationOptions<DeleteReleaseCandidateByNameResponse, DeleteReleaseCandidateByNameError, Options<DeleteReleaseCandidateByNameData>> = {
    mutationFn: async fnOptions => {
      const { data } = await deleteReleaseCandidateByName({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAllReleaseInfosQueryKey = (options?: Options<GetAllReleaseInfosData>) => createQueryKey('getAllReleaseInfos', options);

export const getAllReleaseInfosOptions = (options?: Options<GetAllReleaseInfosData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllReleaseInfos({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllReleaseInfosQueryKey(options),
  });
};

export const createReleaseCandidateMutation = (
  options?: Partial<Options<CreateReleaseCandidateData>>
): MutationOptions<CreateReleaseCandidateResponse, CreateReleaseCandidateError, Options<CreateReleaseCandidateData>> => {
  const mutationOptions: MutationOptions<CreateReleaseCandidateResponse, CreateReleaseCandidateError, Options<CreateReleaseCandidateData>> = {
    mutationFn: async fnOptions => {
      const { data } = await createReleaseCandidate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const publishReleaseDraftMutation = (
  options?: Partial<Options<PublishReleaseDraftData>>
): MutationOptions<unknown, PublishReleaseDraftError, Options<PublishReleaseDraftData>> => {
  const mutationOptions: MutationOptions<unknown, PublishReleaseDraftError, Options<PublishReleaseDraftData>> = {
    mutationFn: async fnOptions => {
      const { data } = await publishReleaseDraft({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const generateReleaseNotesMutation = (
  options?: Partial<Options<GenerateReleaseNotesData>>
): MutationOptions<GenerateReleaseNotesResponse, GenerateReleaseNotesError, Options<GenerateReleaseNotesData>> => {
  const mutationOptions: MutationOptions<GenerateReleaseNotesResponse, GenerateReleaseNotesError, Options<GenerateReleaseNotesData>> = {
    mutationFn: async fnOptions => {
      const { data } = await generateReleaseNotes({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const evaluateMutation = (options?: Partial<Options<EvaluateData>>): MutationOptions<unknown, EvaluateError, Options<EvaluateData>> => {
  const mutationOptions: MutationOptions<unknown, EvaluateError, Options<EvaluateData>> = {
    mutationFn: async fnOptions => {
      const { data } = await evaluate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getReleaseInfoByNameMutation = (
  options?: Partial<Options<GetReleaseInfoByNameData>>
): MutationOptions<GetReleaseInfoByNameResponse, GetReleaseInfoByNameError, Options<GetReleaseInfoByNameData>> => {
  const mutationOptions: MutationOptions<GetReleaseInfoByNameResponse, GetReleaseInfoByNameError, Options<GetReleaseInfoByNameData>> = {
    mutationFn: async fnOptions => {
      const { data } = await getReleaseInfoByName({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const setPrPinnedByNumberMutation = (
  options?: Partial<Options<SetPrPinnedByNumberData>>
): MutationOptions<unknown, SetPrPinnedByNumberError, Options<SetPrPinnedByNumberData>> => {
  const mutationOptions: MutationOptions<unknown, SetPrPinnedByNumberError, Options<SetPrPinnedByNumberData>> = {
    mutationFn: async fnOptions => {
      const { data } = await setPrPinnedByNumber({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const syncEnvironmentsMutation = (
  options?: Partial<Options<SyncEnvironmentsData>>
): MutationOptions<SyncEnvironmentsResponse, SyncEnvironmentsError, Options<SyncEnvironmentsData>> => {
  const mutationOptions: MutationOptions<SyncEnvironmentsResponse, SyncEnvironmentsError, Options<SyncEnvironmentsData>> = {
    mutationFn: async fnOptions => {
      const { data } = await syncEnvironments({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const updateMutation = (options?: Partial<Options<UpdateData>>): MutationOptions<unknown, UpdateError, Options<UpdateData>> => {
  const mutationOptions: MutationOptions<unknown, UpdateError, Options<UpdateData>> = {
    mutationFn: async fnOptions => {
      const { data } = await update({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deployToEnvironmentMutation = (
  options?: Partial<Options<DeployToEnvironmentData>>
): MutationOptions<DeployToEnvironmentResponse, DeployToEnvironmentError, Options<DeployToEnvironmentData>> => {
  const mutationOptions: MutationOptions<DeployToEnvironmentResponse, DeployToEnvironmentError, Options<DeployToEnvironmentData>> = {
    mutationFn: async fnOptions => {
      const { data } = await deployToEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const cancelDeploymentMutation = (
  options?: Partial<Options<CancelDeploymentData>>
): MutationOptions<CancelDeploymentResponse, CancelDeploymentError, Options<CancelDeploymentData>> => {
  const mutationOptions: MutationOptions<CancelDeploymentResponse, CancelDeploymentError, Options<CancelDeploymentData>> = {
    mutationFn: async fnOptions => {
      const { data } = await cancelDeployment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const setBranchPinnedByRepositoryIdAndNameAndUserIdMutation = (
  options?: Partial<Options<SetBranchPinnedByRepositoryIdAndNameAndUserIdData>>
): MutationOptions<unknown, SetBranchPinnedByRepositoryIdAndNameAndUserIdError, Options<SetBranchPinnedByRepositoryIdAndNameAndUserIdData>> => {
  const mutationOptions: MutationOptions<unknown, SetBranchPinnedByRepositoryIdAndNameAndUserIdError, Options<SetBranchPinnedByRepositoryIdAndNameAndUserIdData>> = {
    mutationFn: async fnOptions => {
      const { data } = await setBranchPinnedByRepositoryIdAndNameAndUserId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) => createQueryKey('healthCheck', options);

export const healthCheckOptions = (options?: Options<HealthCheckData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCheckQueryKey(options),
  });
};

export const getAllWorkflowsQueryKey = (options?: Options<GetAllWorkflowsData>) => createQueryKey('getAllWorkflows', options);

export const getAllWorkflowsOptions = (options?: Options<GetAllWorkflowsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllWorkflows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllWorkflowsQueryKey(options),
  });
};

export const getWorkflowByIdQueryKey = (options: Options<GetWorkflowByIdData>) => createQueryKey('getWorkflowById', options);

export const getWorkflowByIdOptions = (options: Options<GetWorkflowByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkflowByIdQueryKey(options),
  });
};

export const getWorkflowsByStateQueryKey = (options: Options<GetWorkflowsByStateData>) => createQueryKey('getWorkflowsByState', options);

export const getWorkflowsByStateOptions = (options: Options<GetWorkflowsByStateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowsByState({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkflowsByStateQueryKey(options),
  });
};

export const getWorkflowsByRepositoryIdQueryKey = (options: Options<GetWorkflowsByRepositoryIdData>) => createQueryKey('getWorkflowsByRepositoryId', options);

export const getWorkflowsByRepositoryIdOptions = (options: Options<GetWorkflowsByRepositoryIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowsByRepositoryId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkflowsByRepositoryIdQueryKey(options),
  });
};

export const getLatestWorkflowRunsByPullRequestIdAndHeadCommitQueryKey = (options: Options<GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData>) =>
  createQueryKey('getLatestWorkflowRunsByPullRequestIdAndHeadCommit', options);

export const getLatestWorkflowRunsByPullRequestIdAndHeadCommitOptions = (options: Options<GetLatestWorkflowRunsByPullRequestIdAndHeadCommitData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestWorkflowRunsByPullRequestIdAndHeadCommit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestWorkflowRunsByPullRequestIdAndHeadCommitQueryKey(options),
  });
};

export const getLatestWorkflowRunsByBranchAndHeadCommitQueryKey = (options: Options<GetLatestWorkflowRunsByBranchAndHeadCommitData>) =>
  createQueryKey('getLatestWorkflowRunsByBranchAndHeadCommit', options);

export const getLatestWorkflowRunsByBranchAndHeadCommitOptions = (options: Options<GetLatestWorkflowRunsByBranchAndHeadCommitData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestWorkflowRunsByBranchAndHeadCommit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestWorkflowRunsByBranchAndHeadCommitQueryKey(options),
  });
};

export const getUserPermissionsQueryKey = (options?: Options<GetUserPermissionsData>) => createQueryKey('getUserPermissions', options);

export const getUserPermissionsOptions = (options?: Options<GetUserPermissionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserPermissionsQueryKey(options),
  });
};

export const getLatestTestResultsByPullRequestIdQueryKey = (options: Options<GetLatestTestResultsByPullRequestIdData>) =>
  createQueryKey('getLatestTestResultsByPullRequestId', options);

export const getLatestTestResultsByPullRequestIdOptions = (options: Options<GetLatestTestResultsByPullRequestIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestTestResultsByPullRequestId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestTestResultsByPullRequestIdQueryKey(options),
  });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getLatestTestResultsByPullRequestIdInfiniteQueryKey = (
  options: Options<GetLatestTestResultsByPullRequestIdData>
): QueryKey<Options<GetLatestTestResultsByPullRequestIdData>> => createQueryKey('getLatestTestResultsByPullRequestId', options, true);

export const getLatestTestResultsByPullRequestIdInfiniteOptions = (options: Options<GetLatestTestResultsByPullRequestIdData>) => {
  return infiniteQueryOptions<
    GetLatestTestResultsByPullRequestIdResponse,
    GetLatestTestResultsByPullRequestIdError,
    InfiniteData<GetLatestTestResultsByPullRequestIdResponse>,
    QueryKey<Options<GetLatestTestResultsByPullRequestIdData>>,
    number | Pick<QueryKey<Options<GetLatestTestResultsByPullRequestIdData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetLatestTestResultsByPullRequestIdData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getLatestTestResultsByPullRequestId({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getLatestTestResultsByPullRequestIdInfiniteQueryKey(options),
    }
  );
};

export const getLatestTestResultsByBranchQueryKey = (options: Options<GetLatestTestResultsByBranchData>) => createQueryKey('getLatestTestResultsByBranch', options);

export const getLatestTestResultsByBranchOptions = (options: Options<GetLatestTestResultsByBranchData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestTestResultsByBranch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestTestResultsByBranchQueryKey(options),
  });
};

export const getLatestTestResultsByBranchInfiniteQueryKey = (options: Options<GetLatestTestResultsByBranchData>): QueryKey<Options<GetLatestTestResultsByBranchData>> =>
  createQueryKey('getLatestTestResultsByBranch', options, true);

export const getLatestTestResultsByBranchInfiniteOptions = (options: Options<GetLatestTestResultsByBranchData>) => {
  return infiniteQueryOptions<
    GetLatestTestResultsByBranchResponse,
    GetLatestTestResultsByBranchError,
    InfiniteData<GetLatestTestResultsByBranchResponse>,
    QueryKey<Options<GetLatestTestResultsByBranchData>>,
    number | Pick<QueryKey<Options<GetLatestTestResultsByBranchData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetLatestTestResultsByBranchData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getLatestTestResultsByBranch({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getLatestTestResultsByBranchInfiniteQueryKey(options),
    }
  );
};

export const getGroupsWithWorkflowsQueryKey = (options: Options<GetGroupsWithWorkflowsData>) => createQueryKey('getGroupsWithWorkflows', options);

export const getGroupsWithWorkflowsOptions = (options: Options<GetGroupsWithWorkflowsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGroupsWithWorkflows({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGroupsWithWorkflowsQueryKey(options),
  });
};

export const getAllRepositoriesQueryKey = (options?: Options<GetAllRepositoriesData>) => createQueryKey('getAllRepositories', options);

export const getAllRepositoriesOptions = (options?: Options<GetAllRepositoriesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllRepositories({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllRepositoriesQueryKey(options),
  });
};

export const getRepositoryByIdQueryKey = (options: Options<GetRepositoryByIdData>) => createQueryKey('getRepositoryById', options);

export const getRepositoryByIdOptions = (options: Options<GetRepositoryByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRepositoryById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRepositoryByIdQueryKey(options),
  });
};

export const getCommitsSinceLastReleaseCandidateQueryKey = (options: Options<GetCommitsSinceLastReleaseCandidateData>) =>
  createQueryKey('getCommitsSinceLastReleaseCandidate', options);

export const getCommitsSinceLastReleaseCandidateOptions = (options: Options<GetCommitsSinceLastReleaseCandidateData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCommitsSinceLastReleaseCandidate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCommitsSinceLastReleaseCandidateQueryKey(options),
  });
};

export const getPullRequestsQueryKey = (options?: Options<GetPullRequestsData>) => createQueryKey('getPullRequests', options);

export const getPullRequestsOptions = (options?: Options<GetPullRequestsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPullRequests({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPullRequestsQueryKey(options),
  });
};

export const getPullRequestsInfiniteQueryKey = (options?: Options<GetPullRequestsData>): QueryKey<Options<GetPullRequestsData>> => createQueryKey('getPullRequests', options, true);

export const getPullRequestsInfiniteOptions = (options?: Options<GetPullRequestsData>) => {
  return infiniteQueryOptions<
    GetPullRequestsResponse,
    GetPullRequestsError,
    InfiniteData<GetPullRequestsResponse>,
    QueryKey<Options<GetPullRequestsData>>,
    number | Pick<QueryKey<Options<GetPullRequestsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetPullRequestsData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPullRequests({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPullRequestsInfiniteQueryKey(options),
    }
  );
};

export const getPullRequestByIdQueryKey = (options: Options<GetPullRequestByIdData>) => createQueryKey('getPullRequestById', options);

export const getPullRequestByIdOptions = (options: Options<GetPullRequestByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPullRequestById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPullRequestByIdQueryKey(options),
  });
};

export const getPullRequestByRepositoryIdAndNumberQueryKey = (options: Options<GetPullRequestByRepositoryIdAndNumberData>) =>
  createQueryKey('getPullRequestByRepositoryIdAndNumber', options);

export const getPullRequestByRepositoryIdAndNumberOptions = (options: Options<GetPullRequestByRepositoryIdAndNumberData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPullRequestByRepositoryIdAndNumber({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPullRequestByRepositoryIdAndNumberQueryKey(options),
  });
};

export const getPullRequestByRepositoryIdQueryKey = (options: Options<GetPullRequestByRepositoryIdData>) => createQueryKey('getPullRequestByRepositoryId', options);

export const getPullRequestByRepositoryIdOptions = (options: Options<GetPullRequestByRepositoryIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPullRequestByRepositoryId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPullRequestByRepositoryIdQueryKey(options),
  });
};

export const getAllEnvironmentsQueryKey = (options?: Options<GetAllEnvironmentsData>) => createQueryKey('getAllEnvironments', options);

export const getAllEnvironmentsOptions = (options?: Options<GetAllEnvironmentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllEnvironments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllEnvironmentsQueryKey(options),
  });
};

export const getEnvironmentReviewersQueryKey = (options: Options<GetEnvironmentReviewersData>) => createQueryKey('getEnvironmentReviewers', options);

export const getEnvironmentReviewersOptions = (options: Options<GetEnvironmentReviewersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentReviewers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentReviewersQueryKey(options),
  });
};

export const getEnvironmentsByUserLockingQueryKey = (options?: Options<GetEnvironmentsByUserLockingData>) => createQueryKey('getEnvironmentsByUserLocking', options);

export const getEnvironmentsByUserLockingOptions = (options?: Options<GetEnvironmentsByUserLockingData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentsByUserLocking({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentsByUserLockingQueryKey(options),
  });
};

export const getEnvironmentsByRepositoryIdQueryKey = (options: Options<GetEnvironmentsByRepositoryIdData>) => createQueryKey('getEnvironmentsByRepositoryId', options);

export const getEnvironmentsByRepositoryIdOptions = (options: Options<GetEnvironmentsByRepositoryIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentsByRepositoryId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentsByRepositoryIdQueryKey(options),
  });
};

export const getLockHistoryByEnvironmentIdQueryKey = (options: Options<GetLockHistoryByEnvironmentIdData>) => createQueryKey('getLockHistoryByEnvironmentId', options);

export const getLockHistoryByEnvironmentIdOptions = (options: Options<GetLockHistoryByEnvironmentIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLockHistoryByEnvironmentId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLockHistoryByEnvironmentIdQueryKey(options),
  });
};

export const getAllEnabledEnvironmentsQueryKey = (options?: Options<GetAllEnabledEnvironmentsData>) => createQueryKey('getAllEnabledEnvironments', options);

export const getAllEnabledEnvironmentsOptions = (options?: Options<GetAllEnabledEnvironmentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllEnabledEnvironments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllEnabledEnvironmentsQueryKey(options),
  });
};

export const getAllDeploymentsQueryKey = (options?: Options<GetAllDeploymentsData>) => createQueryKey('getAllDeployments', options);

export const getAllDeploymentsOptions = (options?: Options<GetAllDeploymentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllDeployments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllDeploymentsQueryKey(options),
  });
};

export const getDeploymentByIdQueryKey = (options: Options<GetDeploymentByIdData>) => createQueryKey('getDeploymentById', options);

export const getDeploymentByIdOptions = (options: Options<GetDeploymentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDeploymentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDeploymentByIdQueryKey(options),
  });
};

export const getWorkflowJobStatusQueryKey = (options: Options<GetWorkflowJobStatusData>) => createQueryKey('getWorkflowJobStatus', options);

export const getWorkflowJobStatusOptions = (options: Options<GetWorkflowJobStatusData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkflowJobStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkflowJobStatusQueryKey(options),
  });
};

export const getDeploymentsByEnvironmentIdQueryKey = (options: Options<GetDeploymentsByEnvironmentIdData>) => createQueryKey('getDeploymentsByEnvironmentId', options);

export const getDeploymentsByEnvironmentIdOptions = (options: Options<GetDeploymentsByEnvironmentIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDeploymentsByEnvironmentId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDeploymentsByEnvironmentIdQueryKey(options),
  });
};

export const getLatestDeploymentByEnvironmentIdQueryKey = (options: Options<GetLatestDeploymentByEnvironmentIdData>) =>
  createQueryKey('getLatestDeploymentByEnvironmentId', options);

export const getLatestDeploymentByEnvironmentIdOptions = (options: Options<GetLatestDeploymentByEnvironmentIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLatestDeploymentByEnvironmentId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLatestDeploymentByEnvironmentIdQueryKey(options),
  });
};

export const getActivityHistoryByEnvironmentIdQueryKey = (options: Options<GetActivityHistoryByEnvironmentIdData>) => createQueryKey('getActivityHistoryByEnvironmentId', options);

export const getActivityHistoryByEnvironmentIdOptions = (options: Options<GetActivityHistoryByEnvironmentIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActivityHistoryByEnvironmentId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActivityHistoryByEnvironmentIdQueryKey(options),
  });
};

export const getCommitByRepositoryIdAndNameQueryKey = (options: Options<GetCommitByRepositoryIdAndNameData>) => createQueryKey('getCommitByRepositoryIdAndName', options);

export const getCommitByRepositoryIdAndNameOptions = (options: Options<GetCommitByRepositoryIdAndNameData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCommitByRepositoryIdAndName({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCommitByRepositoryIdAndNameQueryKey(options),
  });
};

export const getAllBranchesQueryKey = (options?: Options<GetAllBranchesData>) => createQueryKey('getAllBranches', options);

export const getAllBranchesOptions = (options?: Options<GetAllBranchesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAllBranches({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAllBranchesQueryKey(options),
  });
};

export const getBranchByRepositoryIdAndNameQueryKey = (options: Options<GetBranchByRepositoryIdAndNameData>) => createQueryKey('getBranchByRepositoryIdAndName', options);

export const getBranchByRepositoryIdAndNameOptions = (options: Options<GetBranchByRepositoryIdAndNameData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBranchByRepositoryIdAndName({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBranchByRepositoryIdAndNameQueryKey(options),
  });
};

export const deleteWorkflowGroupMutation = (
  options?: Partial<Options<DeleteWorkflowGroupData>>
): MutationOptions<unknown, DeleteWorkflowGroupError, Options<DeleteWorkflowGroupData>> => {
  const mutationOptions: MutationOptions<unknown, DeleteWorkflowGroupError, Options<DeleteWorkflowGroupData>> = {
    mutationFn: async fnOptions => {
      const { data } = await deleteWorkflowGroup({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
