CREATE TABLE public.branch (
    name character varying(255) NOT NULL,
    repository_id bigint NOT NULL,
    ahead_by integer NOT NULL,
    behind_by integer NOT NULL,
    commit_sha character varying(255),
    created_at timestamp(6) with time zone,
    is_default boolean NOT NULL,
    protection boolean NOT NULL,
    updated_at timestamp(6) with time zone,
    updated_by_id bigint
);

CREATE TABLE public.commit (
    repository_id bigint NOT NULL,
    sha character varying(255) NOT NULL,
    authored_at timestamp(6) with time zone,
    message character varying(1023),
    author_id bigint
);

CREATE TABLE public.data_sync_status (
    id bigint NOT NULL,
    end_time timestamp(6) with time zone,
    start_time timestamp(6) with time zone
);

ALTER TABLE public.data_sync_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_sync_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.deployment (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    environment_name character varying(255),
    node_id character varying(255),
    ref character varying(255),
    repository_url character varying(255),
    sha character varying(255),
    state character varying(255),
    statuses_url character varying(255),
    task character varying(255),
    url character varying(255),
    repository_id bigint,
    environment_id bigint NOT NULL,
    pull_request_id bigint,
    CONSTRAINT deployment_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'ERROR'::character varying, 'FAILURE'::character varying, 'IN_PROGRESS'::character varying, 'QUEUED'::character varying, 'INACTIVE'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE public.environment (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    deployed_at timestamp(6) with time zone,
    description character varying(255),
    enabled boolean NOT NULL,
    html_url character varying(255),
    locked boolean NOT NULL,
    locked_at timestamp(6) with time zone,
    locked_by character varying(255),
    name character varying(255) NOT NULL,
    server_url character varying(255),
    updated_at timestamp(6) with time zone,
    url character varying(255),
    version integer,
    repository_id bigint
);

CREATE TABLE public.environment_lock_history (
    id bigint NOT NULL,
    locked_at timestamp(6) with time zone,
    locked_by character varying(255),
    unlocked_at timestamp(6) with time zone,
    environment_id bigint
);

ALTER TABLE public.environment_lock_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.environment_lock_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.helios_deployment (
    id bigint NOT NULL,
    branch_name character varying(255),
    build_tag character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    status_updated_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    triggering_user character varying(255) NOT NULL,
    workflow_params jsonb,
    environment_id bigint NOT NULL,
    CONSTRAINT helios_deployment_status_check CHECK (((status)::text = ANY ((ARRAY['WAITING'::character varying, 'QUEUED'::character varying, 'IN_PROGRESS'::character varying, 'DEPLOYMENT_SUCCESS'::character varying, 'FAILED'::character varying, 'IO_ERROR'::character varying, 'UNKNOWN'::character varying])::text[])))
);

ALTER TABLE public.helios_deployment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.helios_deployment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.installed_apps (
    environment_id bigint NOT NULL,
    app_name character varying(255)
);

CREATE TABLE public.issue (
    issue_type character varying(31) NOT NULL,
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    body oid,
    closed_at timestamp(6) with time zone,
    comments_count integer NOT NULL,
    html_url character varying(255),
    is_locked boolean NOT NULL,
    number integer NOT NULL,
    state character varying(255),
    title character varying(255),
    additions integer,
    changed_files integer,
    commits integer,
    deletions integer,
    head_ref_name character varying(255),
    head_ref_repo_name_with_owner character varying(255),
    head_sha character varying(255),
    is_draft boolean,
    is_mergeable boolean,
    is_merged boolean,
    maintainer_can_modify boolean,
    merge_commit_sha character varying(255),
    mergeable_state character varying(255),
    merged_at timestamp(6) with time zone,
    repository_id bigint,
    author_id bigint,
    merged_by_id bigint,
    CONSTRAINT issue_state_check CHECK (((state)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);

CREATE TABLE public.issue_assignee (
    issue_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.issue_label (
    issue_id bigint NOT NULL,
    label_id bigint NOT NULL
);

CREATE TABLE public.issue_workflow_runs (
    pull_request_id bigint NOT NULL,
    workflow_runs_id bigint NOT NULL
);

CREATE TABLE public.label (
    id bigint NOT NULL,
    color character varying(255),
    description character varying(255),
    name character varying(255),
    repository_id bigint
);

CREATE TABLE public.pull_request_requested_reviewers (
    pull_request_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.repository (
    repository_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    default_branch character varying(255),
    description character varying(255),
    has_issues boolean NOT NULL,
    has_projects boolean NOT NULL,
    has_wiki boolean NOT NULL,
    homepage character varying(255),
    html_url character varying(255),
    is_archived boolean NOT NULL,
    is_disabled boolean NOT NULL,
    is_private boolean NOT NULL,
    name character varying(255),
    name_with_owner character varying(255),
    pushed_at timestamp(6) with time zone,
    stargazers_count integer NOT NULL,
    updated_at timestamp(6) with time zone,
    visibility character varying(255),
    watchers_count integer NOT NULL,
    CONSTRAINT repository_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'INTERNAL'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE public.repository_settings (
    id bigint NOT NULL,
    repository_id bigint
);

ALTER TABLE public.repository_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repository_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."user" (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    avatar_url character varying(255),
    blog character varying(255),
    company character varying(255),
    description character varying(255),
    email character varying(255),
    followers integer NOT NULL,
    following integer NOT NULL,
    html_url character varying(255),
    location character varying(255),
    login character varying(255),
    name character varying(255),
    type character varying(255),
    repository_id bigint,
    CONSTRAINT user_type_check CHECK (((type)::text = ANY ((ARRAY['USER'::character varying, 'ORGANIZATION'::character varying, 'BOT'::character varying])::text[])))
);

CREATE TABLE public.workflow (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    badge_url character varying(255),
    file_name_with_extension character varying(255),
    html_url character varying(255),
    label character varying(255),
    name character varying(255),
    path character varying(255),
    state character varying(255),
    url character varying(255),
    repository_id bigint,
    CONSTRAINT workflow_label_check CHECK (((label)::text = ANY ((ARRAY['BUILD'::character varying, 'DEPLOYMENT'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT workflow_state_check CHECK (((state)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying, 'DISABLED_FORK'::character varying, 'DISABLED_INACTIVITY'::character varying, 'DISABLED_MANUALLY'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE public.workflow_group (
    id bigint NOT NULL,
    name character varying(255),
    order_index integer NOT NULL,
    repository_settings_id bigint
);

ALTER TABLE public.workflow_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workflow_group_membership (
    id bigint NOT NULL,
    order_index integer NOT NULL,
    workflow_id bigint,
    workflow_group_id bigint
);

ALTER TABLE public.workflow_group_membership ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_group_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workflow_run (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    artifacts_url character varying(255),
    cancel_url character varying(255),
    check_suite_url character varying(255),
    conclusion character varying(255),
    display_title character varying(255),
    head_branch character varying(255),
    head_sha character varying(255),
    html_url character varying(255),
    jobs_url character varying(255),
    logs_url character varying(255),
    name character varying(255),
    rerun_url character varying(255),
    run_attempt bigint NOT NULL,
    run_number bigint NOT NULL,
    run_started_at timestamp(6) with time zone,
    status character varying(255),
    workflow_id bigint NOT NULL,
    workflow_url character varying(255),
    repository_id bigint,
    CONSTRAINT workflow_run_conclusion_check CHECK (((conclusion)::text = ANY ((ARRAY['ACTION_REQUIRED'::character varying, 'CANCELLED'::character varying, 'FAILURE'::character varying, 'NEUTRAL'::character varying, 'SUCCESS'::character varying, 'SKIPPED'::character varying, 'STALE'::character varying, 'TIMED_OUT'::character varying, 'STARTUP_FAILURE'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT workflow_run_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'ACTION_REQUIRED'::character varying, 'CANCELLED'::character varying, 'FAILURE'::character varying, 'NEUTRAL'::character varying, 'SKIPPED'::character varying, 'STALE'::character varying, 'SUCCESS'::character varying, 'TIMED_OUT'::character varying, 'REQUESTED'::character varying, 'WAITING'::character varying, 'PENDING'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE public.workflow_run_pull_requests (
    workflow_run_id bigint NOT NULL,
    pull_requests_id bigint NOT NULL
);

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT branch_pkey PRIMARY KEY (name, repository_id);

ALTER TABLE ONLY public.commit
    ADD CONSTRAINT commit_pkey PRIMARY KEY (repository_id, sha);

ALTER TABLE ONLY public.data_sync_status
    ADD CONSTRAINT data_sync_status_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.environment_lock_history
    ADD CONSTRAINT environment_lock_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.environment
    ADD CONSTRAINT environment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.helios_deployment
    ADD CONSTRAINT helios_deployment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_assignee
    ADD CONSTRAINT issue_assignee_pkey PRIMARY KEY (issue_id, user_id);

ALTER TABLE ONLY public.issue_label
    ADD CONSTRAINT issue_label_pkey PRIMARY KEY (issue_id, label_id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT issue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.issue_workflow_runs
    ADD CONSTRAINT issue_workflow_runs_pkey PRIMARY KEY (pull_request_id, workflow_runs_id);

ALTER TABLE ONLY public.label
    ADD CONSTRAINT label_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pull_request_requested_reviewers
    ADD CONSTRAINT pull_request_requested_reviewers_pkey PRIMARY KEY (pull_request_id, user_id);

ALTER TABLE ONLY public.repository
    ADD CONSTRAINT repository_pkey PRIMARY KEY (repository_id);

ALTER TABLE ONLY public.repository_settings
    ADD CONSTRAINT repository_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_group
    ADD CONSTRAINT ukrem30xy4q5le9gc3cfn8y4j3a UNIQUE (repository_settings_id, order_index);

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_group_membership
    ADD CONSTRAINT workflow_group_membership_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_group
    ADD CONSTRAINT workflow_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT workflow_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_run
    ADD CONSTRAINT workflow_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workflow_run_pull_requests
    ADD CONSTRAINT workflow_run_pull_requests_pkey PRIMARY KEY (workflow_run_id, pull_requests_id);

ALTER TABLE ONLY public.workflow
    ADD CONSTRAINT fk279rn80j1a5ddkj04bemt907w FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.label
    ADD CONSTRAINT fk2951edbl9g9y8ee1q97e2ff75 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.issue_assignee
    ADD CONSTRAINT fk2cfu8w8wjb9vosy4hbrme0rqe FOREIGN KEY (user_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT fk2wdyfioym1epj5p2f1lgsl7dx FOREIGN KEY (environment_id) REFERENCES public.environment(id);

ALTER TABLE ONLY public.workflow_run
    ADD CONSTRAINT fk3rcdfx1e2c3yrvadr98pxn2m2 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.commit
    ADD CONSTRAINT fk4c4goeh7k2c5kyso5kteinmrd FOREIGN KEY (author_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.pull_request_requested_reviewers
    ADD CONSTRAINT fk6dld06xx8rh9xhqfnca070a0i FOREIGN KEY (pull_request_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fk76s4b6ncspm9bk35y49xh4s9t FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT fk8oj2schxrppdeen7kvngiqcf4 FOREIGN KEY (updated_by_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.workflow_run_pull_requests
    ADD CONSTRAINT fkb4tp79ihvjiuqi4lbx8gqvqih FOREIGN KEY (pull_requests_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.environment_lock_history
    ADD CONSTRAINT fkb7t7o88en911u1wjg59ldt75b FOREIGN KEY (environment_id) REFERENCES public.environment(id);

ALTER TABLE ONLY public.issue_workflow_runs
    ADD CONSTRAINT fkbcqvyqbndm5422rxf58vd134g FOREIGN KEY (workflow_runs_id) REFERENCES public.workflow_run(id);

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT fkbjy892k9b0c92wvqc407cda3b FOREIGN KEY (pull_request_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.workflow_run_pull_requests
    ADD CONSTRAINT fkbpd29gs51yccp7xydinuexlw FOREIGN KEY (workflow_run_id) REFERENCES public.workflow_run(id);

ALTER TABLE ONLY public.workflow_group_membership
    ADD CONSTRAINT fkbyyf2o04x82pud4fbaylfhyoy FOREIGN KEY (workflow_group_id) REFERENCES public.workflow_group(id);

ALTER TABLE ONLY public.branch
    ADD CONSTRAINT fkeebb6nxm58bea44qso7p3ehu4 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.repository_settings
    ADD CONSTRAINT fkg5gupw73hms8gs1yblxw6x6mv FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.commit
    ADD CONSTRAINT fkgqmkfk1wovdbkmbanfrrxc9pp FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.pull_request_requested_reviewers
    ADD CONSTRAINT fkioq4g5aksr97l6qyl4g5l63tn FOREIGN KEY (user_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.issue_label
    ADD CONSTRAINT fkit5n9c0frugu5m8xqsxtps63r FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.workflow_group_membership
    ADD CONSTRAINT fkixdlgaqu4hykyehs17gbvyvfj FOREIGN KEY (workflow_id) REFERENCES public.workflow(id);

ALTER TABLE ONLY public.issue_workflow_runs
    ADD CONSTRAINT fkk489xsqux2u0oh20ax532hu40 FOREIGN KEY (pull_request_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.environment
    ADD CONSTRAINT fklifflq2nvs3cfi5gh23u5kg45 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.workflow_group
    ADD CONSTRAINT fklu121d5bqgup9xi7va5jyqqq7 FOREIGN KEY (repository_settings_id) REFERENCES public.repository_settings(id);

ALTER TABLE ONLY public.issue_assignee
    ADD CONSTRAINT fkocgmsva4p5e8ic9k5dbjqa15u FOREIGN KEY (issue_id) REFERENCES public.issue(id);

ALTER TABLE ONLY public.installed_apps
    ADD CONSTRAINT fkpfj5pd1sbcahyiitsl8ce8vvb FOREIGN KEY (environment_id) REFERENCES public.environment(id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkqvnu6vslj5txt8xencru8m6x4 FOREIGN KEY (merged_by_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fkr57jb1y82r0hx92dvghky0262 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.issue
    ADD CONSTRAINT fkrwr6v8fiqetuiuvfjcvie8s85 FOREIGN KEY (author_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT fksjgd2dgfjwp7moqk366hg8c04 FOREIGN KEY (repository_id) REFERENCES public.repository(repository_id);

ALTER TABLE ONLY public.helios_deployment
    ADD CONSTRAINT fkt970s49c8fv0vdnw2ssovbpia FOREIGN KEY (environment_id) REFERENCES public.environment(id);

ALTER TABLE ONLY public.issue_label
    ADD CONSTRAINT fkxbk5rr30kkb6k4ech7x4vh9h FOREIGN KEY (label_id) REFERENCES public.label(id);
