create table
    tag (
        name varchar(255) not null,
        created_at timestamp(6)
        with
            time zone,
            repository_id bigint not null,
            branch_name varchar(255),
            branch_repository_id bigint,
            commit_repository_id bigint not null,
            commit_sha varchar(255) not null,
            created_by_id bigint,
            primary key (name, repository_id)
    );

create table
    tag_evaluations (
        tag_name varchar(255) not null,
        tag_repository_id bigint not null,
        evaluations_id bigint not null,
        primary key (tag_name, tag_repository_id, evaluations_id)
    );

create table
    tag_evaluation (
        id bigint not null,
        is_working boolean not null,
        evaluated_by_id bigint,
        primary key (id)
    );

ALTER TABLE public.tag_evaluation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

alter table only tag add constraint pkey_branch_name_repository_id unique (branch_name, branch_repository_id);
alter table only tag add constraint pkey_commit_repository_id_commit_sha unique (commit_repository_id, commit_sha);
alter table only tag_evaluations add constraint pkey_evaluations_id unique (evaluations_id);
alter table only tag add constraint FKdj9bgiudh8pae58vb7k1hy4pq foreign key (repository_id) references repository;
alter table only tag add constraint FKtpgs4u8l5skgjlr95atu96yqt foreign key (branch_repository_id, branch_name) references branch;
alter table only tag add constraint FK3o93c1y4ayqlobwid7ipkc2l4 foreign key (commit_repository_id, commit_sha) references commit;
alter table only tag add constraint FKlvm85yfqra0n9dmqrfaeqh2hj foreign key (created_by_id) references public.user;
alter table only tag_evaluations add constraint FK325o9vn1ue6c6qbiopfpf5nkx foreign key (evaluations_id) references tag_evaluation;
alter table only tag_evaluations add constraint FKnv2toh0qu24n5a6t4u5mgo0yw foreign key (tag_name, tag_repository_id) references tag;
alter table only tag_evaluation add constraint FKerigvj8hd9wn6jg8ahgjhxnbf foreign key (evaluated_by_id) references public.user;
alter table only public.user add constraint unique_user_login unique (login);
