-- Per-repository pipeline configuration. pipeline_category holds the ordered stage lanes
-- (Build/Test/Quality) for a repository (via repository_settings), pipeline_node holds the ordered
-- nodes within a lane, and pipeline_node_job_matcher is the @ElementCollection of job-name prefixes
-- a node matches. Mirrors the workflow_group ordering conventions (IDENTITY id, unique
-- (parent, order_index)). Replaces the global helios.pipeline catalog with per-repo, DB-stored config.

CREATE TABLE public.pipeline_category (
    id bigint NOT NULL,
    repository_settings_id bigint,
    name character varying(255) NOT NULL,
    order_index integer NOT NULL,
    CONSTRAINT pipeline_category_pkey PRIMARY KEY (id),
    CONSTRAINT uk_pipeline_category_settings_order UNIQUE (repository_settings_id, order_index)
);

ALTER TABLE public.pipeline_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pipeline_node (
    id bigint NOT NULL,
    pipeline_category_id bigint,
    node_key character varying(255) NOT NULL,
    label character varying(255) NOT NULL,
    workflow_name_matcher character varying(255),
    order_index integer NOT NULL,
    CONSTRAINT pipeline_node_pkey PRIMARY KEY (id),
    CONSTRAINT uk_pipeline_node_category_order UNIQUE (pipeline_category_id, order_index)
);

ALTER TABLE public.pipeline_node ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pipeline_node_job_matcher (
    pipeline_node_id bigint NOT NULL,
    matcher character varying(255)
);

ALTER TABLE ONLY public.pipeline_category
    ADD CONSTRAINT fk_pipeline_category_settings FOREIGN KEY (repository_settings_id)
        REFERENCES public.repository_settings(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pipeline_node
    ADD CONSTRAINT fk_pipeline_node_category FOREIGN KEY (pipeline_category_id)
        REFERENCES public.pipeline_category(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pipeline_node_job_matcher
    ADD CONSTRAINT fk_pipeline_node_job_matcher_node FOREIGN KEY (pipeline_node_id)
        REFERENCES public.pipeline_node(id) ON DELETE CASCADE;

CREATE INDEX idx_pipeline_category_repository_settings
    ON public.pipeline_category (repository_settings_id);

CREATE INDEX idx_pipeline_node_category ON public.pipeline_node (pipeline_category_id);

CREATE INDEX idx_pipeline_node_job_matcher_node
    ON public.pipeline_node_job_matcher (pipeline_node_id);
