name: Release to Sentry

on:
  workflow_call:
    inputs:
      client_image_tag:
        default: "latest"
        type: string

permissions:
  contents: read
  packages: read

jobs:
  release-client-sentry:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run
        uses: tj-actions/docker-run@1d25a677da8f1243a138dc5db21e307e92986ffe  # v2.2.1
        id: docker-run
        with:
          image: ghcr.io/ls1intum/helios/client:${{ inputs.client_image_tag }}
          name: client-build
          options: -d
          args: sleep 10
      - name: Copy from container to host
        uses: tj-actions/docker-cp@4b9e349aae3e214557fa24d65bd2683f07277e72  # v2.0.2
        with:
          container: ${{ steps.docker-run.outputs.container-id }}
          source: /usr/share/nginx/html
          destination: ./dist
      - name: Create Sentry release for Client
        uses: getsentry/action-release@f71adb49d4b2aeeda98052d3de234bbb0f3e03ab  # v3.6.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_CLIENT_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
        with:
          environment: production
          version: ${{ github.ref_name }}
          sourcemaps: "./dist"
  release-server-sentry:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create Sentry release for Server
        uses: getsentry/action-release@f71adb49d4b2aeeda98052d3de234bbb0f3e03ab  # v3.6.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_SERVER_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
        with:
          environment: production
          version: ${{ github.ref_name }}
